# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ApplicationWindow.ui'
#
# Created by: PyQt5 UI code generator 5.9.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class ApplicationForm(object):
    def setupUi(self, main_app_window):
        main_app_window.setObjectName("main_app_window")
        main_app_window.setWindowModality(QtCore.Qt.NonModal)
        main_app_window.resize(868, 652)
        main_app_window.setCentralWidget
        self.centralwidget = QtWidgets.QWidget(main_app_window)
        self.centralwidget.setObjectName("centralwidget")
        self.tab_widget = QtWidgets.QTabWidget(self.centralwidget)
        self.tab_widget.setGeometry(QtCore.QRect(10, 10, 811, 511))
        self.tab_widget.setObjectName("tab_widget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayoutWidget = QtWidgets.QWidget(self.tab)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(20, 120, 135, 160))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.gridLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.find_patient_bttn = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.find_patient_bttn.setObjectName("find_patient_bttn")
        self.verticalLayout.addWidget(self.find_patient_bttn)
        self.name_label = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.name_label.setFont(font)
        self.name_label.setAlignment(QtCore.Qt.AlignCenter)
        self.name_label.setObjectName("name_label")
        self.verticalLayout.addWidget(self.name_label)
        self.name_le = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.name_le.setObjectName("name_le")
        self.verticalLayout.addWidget(self.name_le)
        self.surname_label = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.surname_label.setFont(font)
        self.surname_label.setAutoFillBackground(False)
        self.surname_label.setTextFormat(QtCore.Qt.AutoText)
        self.surname_label.setScaledContents(False)
        self.surname_label.setAlignment(QtCore.Qt.AlignCenter)
        self.surname_label.setObjectName("surname_label")
        self.verticalLayout.addWidget(self.surname_label)
        self.surname_le = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.surname_le.setObjectName("surname_le")
        self.verticalLayout.addWidget(self.surname_le)
        self.pesel_name = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pesel_name.setFont(font)
        self.pesel_name.setAlignment(QtCore.Qt.AlignCenter)
        self.pesel_name.setObjectName("pesel_name")
        self.verticalLayout.addWidget(self.pesel_name)
        self.pesel_le = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.pesel_le.setObjectName("pesel_le")
        self.verticalLayout.addWidget(self.pesel_le)
        self.main_table = QtWidgets.QTableView(self.tab)
        self.main_table.setGeometry(QtCore.QRect(250, 30, 511, 411))
        self.main_table.setObjectName("main_table")
        self.tab_widget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.main_table_func = QtWidgets.QTableView(self.tab_2)
        self.main_table_func.setGeometry(QtCore.QRect(180, 30, 511, 411))
        self.main_table_func.setObjectName("main_table_func")
        self.find_patient_bttn_func = QtWidgets.QPushButton(self.tab_2)
        self.find_patient_bttn_func.setGeometry(QtCore.QRect(20, 190, 121, 23))
        self.find_patient_bttn_func.setObjectName("find_patient_bttn_func")
        self.tab_widget.addTab(self.tab_2, "")
        main_app_window.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(main_app_window)
        self.statusbar.setObjectName("statusbar")
        main_app_window.setStatusBar(self.statusbar)

        self.retranslateUi(main_app_window)
        self.tab_widget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(main_app_window)

    def retranslateUi(self, main_app_window):
        _translate = QtCore.QCoreApplication.translate
        main_app_window.setWindowTitle(_translate("main_app_window", "MainWindow"))
        self.find_patient_bttn.setText(_translate("main_app_window", "FindMeAPatient"))
        self.name_label.setText(_translate("main_app_window", "Name"))
        self.surname_label.setText(_translate("main_app_window", "Surname"))
        self.pesel_name.setText(_translate("main_app_window", "PESEL"))
        self.tab_widget.setTabText(self.tab_widget.indexOf(self.tab), _translate("main_app_window", "General"))
        self.find_patient_bttn_func.setText(_translate("main_app_window", "IAlsoWantToWork"))
        self.tab_widget.setTabText(self.tab_widget.indexOf(self.tab_2), _translate("main_app_window", "Functions"))

