# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ApplicationWindow2.ui'
#
# Created by: PyQt5 UI code generator 5.4.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_main_app_window(object):
    def setupUi(self, main_app_window):
        main_app_window.setObjectName("main_app_window")
        main_app_window.setWindowModality(QtCore.Qt.NonModal)
        main_app_window.resize(1206, 740)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(main_app_window.sizePolicy().hasHeightForWidth())
        main_app_window.setSizePolicy(sizePolicy)
        self.centralwidget = QtWidgets.QWidget(main_app_window)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.tab_widget = QtWidgets.QTabWidget(self.centralwidget)
        self.tab_widget.setStyleSheet("")
        self.tab_widget.setObjectName("tab_widget")
        self.general_tab = QtWidgets.QWidget()
        self.general_tab.setObjectName("general_tab")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.general_tab)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label = QtWidgets.QLabel(self.general_tab)
        self.label.setMaximumSize(QtCore.QSize(16777215, 100))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setTextFormat(QtCore.Qt.RichText)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setWordWrap(False)
        self.label.setObjectName("label")
        self.gridLayout_3.addWidget(self.label, 0, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.general_tab)
        self.label_2.setObjectName("label_2")
        self.gridLayout_3.addWidget(self.label_2, 1, 0, 1, 1)
        self.gridLayout_7.addLayout(self.gridLayout_3, 0, 0, 1, 1)
        self.tab_widget.addTab(self.general_tab, "")
        self.credentials_tab = QtWidgets.QWidget()
        self.credentials_tab.setObjectName("credentials_tab")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.credentials_tab)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.findpatient_layout = QtWidgets.QGridLayout()
        self.findpatient_layout.setObjectName("findpatient_layout")
        self.findpatient_search_button = QtWidgets.QPushButton(self.credentials_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.findpatient_search_button.sizePolicy().hasHeightForWidth())
        self.findpatient_search_button.setSizePolicy(sizePolicy)
        self.findpatient_search_button.setObjectName("findpatient_search_button")
        self.findpatient_layout.addWidget(self.findpatient_search_button, 4, 0, 1, 1)
        self.findpatient_label = QtWidgets.QLabel(self.credentials_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.findpatient_label.sizePolicy().hasHeightForWidth())
        self.findpatient_label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        self.findpatient_label.setFont(font)
        self.findpatient_label.setAutoFillBackground(False)
        self.findpatient_label.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.findpatient_label.setFrameShadow(QtWidgets.QFrame.Raised)
        self.findpatient_label.setLineWidth(4)
        self.findpatient_label.setMidLineWidth(2)
        self.findpatient_label.setAlignment(QtCore.Qt.AlignCenter)
        self.findpatient_label.setWordWrap(False)
        self.findpatient_label.setContentsMargins(1, 1, 1, 1)
        self.findpatient_label.setIndent(-1)
        self.findpatient_label.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.findpatient_label.setObjectName("findpatient_label")
        self.findpatient_layout.addWidget(self.findpatient_label, 1, 0, 1, 1)
        self.findpatient_tab_widget = QtWidgets.QTabWidget(self.credentials_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.findpatient_tab_widget.sizePolicy().hasHeightForWidth())
        self.findpatient_tab_widget.setSizePolicy(sizePolicy)
        self.findpatient_tab_widget.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.findpatient_tab_widget.setElideMode(QtCore.Qt.ElideLeft)
        self.findpatient_tab_widget.setObjectName("findpatient_tab_widget")
        self.basic_param_tab = QtWidgets.QWidget()
        self.basic_param_tab.setObjectName("basic_param_tab")
        self.gridLayoutWidget_6 = QtWidgets.QWidget(self.basic_param_tab)
        self.gridLayoutWidget_6.setGeometry(QtCore.QRect(0, 0, 191, 171))
        self.gridLayoutWidget_6.setObjectName("gridLayoutWidget_6")
        self.findpatient_basic_layout = QtWidgets.QGridLayout(self.gridLayoutWidget_6)
        self.findpatient_basic_layout.setContentsMargins(0, 0, 0, 0)
        self.findpatient_basic_layout.setObjectName("findpatient_basic_layout")
        self.pesel_le = QtWidgets.QLineEdit(self.gridLayoutWidget_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pesel_le.sizePolicy().hasHeightForWidth())
        self.pesel_le.setSizePolicy(sizePolicy)
        self.pesel_le.setObjectName("pesel_le")
        self.findpatient_basic_layout.addWidget(self.pesel_le, 7, 0, 1, 1)
        self.surname_le = QtWidgets.QLineEdit(self.gridLayoutWidget_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.surname_le.sizePolicy().hasHeightForWidth())
        self.surname_le.setSizePolicy(sizePolicy)
        self.surname_le.setObjectName("surname_le")
        self.findpatient_basic_layout.addWidget(self.surname_le, 4, 0, 1, 1)
        self.name_label = QtWidgets.QLabel(self.gridLayoutWidget_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.name_label.sizePolicy().hasHeightForWidth())
        self.name_label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.name_label.setFont(font)
        self.name_label.setAlignment(QtCore.Qt.AlignCenter)
        self.name_label.setObjectName("name_label")
        self.findpatient_basic_layout.addWidget(self.name_label, 0, 0, 1, 1)
        self.name_le = QtWidgets.QLineEdit(self.gridLayoutWidget_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.name_le.sizePolicy().hasHeightForWidth())
        self.name_le.setSizePolicy(sizePolicy)
        self.name_le.setObjectName("name_le")
        self.findpatient_basic_layout.addWidget(self.name_le, 1, 0, 1, 1)
        self.pesel_label = QtWidgets.QLabel(self.gridLayoutWidget_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pesel_label.sizePolicy().hasHeightForWidth())
        self.pesel_label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pesel_label.setFont(font)
        self.pesel_label.setAlignment(QtCore.Qt.AlignCenter)
        self.pesel_label.setObjectName("pesel_label")
        self.findpatient_basic_layout.addWidget(self.pesel_label, 5, 0, 1, 1)
        self.surname_label = QtWidgets.QLabel(self.gridLayoutWidget_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.surname_label.sizePolicy().hasHeightForWidth())
        self.surname_label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.surname_label.setFont(font)
        self.surname_label.setAutoFillBackground(False)
        self.surname_label.setTextFormat(QtCore.Qt.AutoText)
        self.surname_label.setScaledContents(False)
        self.surname_label.setAlignment(QtCore.Qt.AlignCenter)
        self.surname_label.setObjectName("surname_label")
        self.findpatient_basic_layout.addWidget(self.surname_label, 2, 0, 1, 1)
        self.findpatient_tab_widget.addTab(self.basic_param_tab, "")
        self.adv_param_tab = QtWidgets.QWidget()
        self.adv_param_tab.setObjectName("adv_param_tab")
        self.gridLayoutWidget_5 = QtWidgets.QWidget(self.adv_param_tab)
        self.gridLayoutWidget_5.setGeometry(QtCore.QRect(0, 0, 191, 314))
        self.gridLayoutWidget_5.setObjectName("gridLayoutWidget_5")
        self.findpatient_adv_layout = QtWidgets.QGridLayout(self.gridLayoutWidget_5)
        self.findpatient_adv_layout.setContentsMargins(0, 0, 0, 0)
        self.findpatient_adv_layout.setObjectName("findpatient_adv_layout")
        self.gender_label = QtWidgets.QLabel(self.gridLayoutWidget_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gender_label.sizePolicy().hasHeightForWidth())
        self.gender_label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.gender_label.setFont(font)
        self.gender_label.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.gender_label.setObjectName("gender_label")
        self.findpatient_adv_layout.addWidget(self.gender_label, 2, 0, 1, 1)
        self.city_label = QtWidgets.QLabel(self.gridLayoutWidget_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.city_label.sizePolicy().hasHeightForWidth())
        self.city_label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.city_label.setFont(font)
        self.city_label.setAlignment(QtCore.Qt.AlignCenter)
        self.city_label.setObjectName("city_label")
        self.findpatient_adv_layout.addWidget(self.city_label, 8, 0, 1, 1)
        self.phonenumber_label = QtWidgets.QLabel(self.gridLayoutWidget_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.phonenumber_label.sizePolicy().hasHeightForWidth())
        self.phonenumber_label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.phonenumber_label.setFont(font)
        self.phonenumber_label.setAlignment(QtCore.Qt.AlignCenter)
        self.phonenumber_label.setObjectName("phonenumber_label")
        self.findpatient_adv_layout.addWidget(self.phonenumber_label, 6, 0, 1, 1)
        self.phonenumber_le = QtWidgets.QLineEdit(self.gridLayoutWidget_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.phonenumber_le.sizePolicy().hasHeightForWidth())
        self.phonenumber_le.setSizePolicy(sizePolicy)
        self.phonenumber_le.setObjectName("phonenumber_le")
        self.findpatient_adv_layout.addWidget(self.phonenumber_le, 7, 0, 1, 1)
        self.postalcode_label = QtWidgets.QLabel(self.gridLayoutWidget_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.postalcode_label.sizePolicy().hasHeightForWidth())
        self.postalcode_label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.postalcode_label.setFont(font)
        self.postalcode_label.setAlignment(QtCore.Qt.AlignCenter)
        self.postalcode_label.setObjectName("postalcode_label")
        self.findpatient_adv_layout.addWidget(self.postalcode_label, 10, 0, 1, 1)
        self.city_le = QtWidgets.QLineEdit(self.gridLayoutWidget_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.city_le.sizePolicy().hasHeightForWidth())
        self.city_le.setSizePolicy(sizePolicy)
        self.city_le.setObjectName("city_le")
        self.findpatient_adv_layout.addWidget(self.city_le, 9, 0, 1, 1)
        self.country_cb = QtWidgets.QComboBox(self.gridLayoutWidget_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.country_cb.sizePolicy().hasHeightForWidth())
        self.country_cb.setSizePolicy(sizePolicy)
        self.country_cb.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContents)
        self.country_cb.setObjectName("country_cb")
        self.country_cb.addItem("")
        self.country_cb.setItemText(0, "")
        self.country_cb.addItem("")
        self.country_cb.addItem("")
        self.country_cb.addItem("")
        self.country_cb.addItem("")
        self.country_cb.addItem("")
        self.country_cb.addItem("")
        self.country_cb.addItem("")
        self.country_cb.addItem("")
        self.country_cb.addItem("")
        self.country_cb.addItem("")
        self.country_cb.addItem("")
        self.findpatient_adv_layout.addWidget(self.country_cb, 5, 0, 1, 1)
        self.country_label = QtWidgets.QLabel(self.gridLayoutWidget_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.country_label.sizePolicy().hasHeightForWidth())
        self.country_label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.country_label.setFont(font)
        self.country_label.setAlignment(QtCore.Qt.AlignCenter)
        self.country_label.setObjectName("country_label")
        self.findpatient_adv_layout.addWidget(self.country_label, 4, 0, 1, 1)
        self.postalcode_le = QtWidgets.QLineEdit(self.gridLayoutWidget_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.postalcode_le.sizePolicy().hasHeightForWidth())
        self.postalcode_le.setSizePolicy(sizePolicy)
        self.postalcode_le.setObjectName("postalcode_le")
        self.findpatient_adv_layout.addWidget(self.postalcode_le, 11, 0, 1, 1)
        self.gender_cb = QtWidgets.QComboBox(self.gridLayoutWidget_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gender_cb.sizePolicy().hasHeightForWidth())
        self.gender_cb.setSizePolicy(sizePolicy)
        self.gender_cb.setObjectName("gender_cb")
        self.gender_cb.addItem("")
        self.gender_cb.setItemText(0, "")
        self.gender_cb.addItem("")
        self.gender_cb.addItem("")
        self.findpatient_adv_layout.addWidget(self.gender_cb, 3, 0, 1, 1)
        self.dateofbirth_label = QtWidgets.QLabel(self.gridLayoutWidget_5)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.dateofbirth_label.setFont(font)
        self.dateofbirth_label.setAlignment(QtCore.Qt.AlignCenter)
        self.dateofbirth_label.setObjectName("dateofbirth_label")
        self.findpatient_adv_layout.addWidget(self.dateofbirth_label, 0, 0, 1, 1)
        self.dateofbirth_le = QtWidgets.QLineEdit(self.gridLayoutWidget_5)
        self.dateofbirth_le.setObjectName("dateofbirth_le")
        self.findpatient_adv_layout.addWidget(self.dateofbirth_le, 1, 0, 1, 1)
        self.findpatient_tab_widget.addTab(self.adv_param_tab, "")
        self.findpatient_layout.addWidget(self.findpatient_tab_widget, 3, 0, 1, 1)
        self.findpatient_showall_button = QtWidgets.QPushButton(self.credentials_tab)
        self.findpatient_showall_button.setObjectName("findpatient_showall_button")
        self.findpatient_layout.addWidget(self.findpatient_showall_button, 5, 0, 1, 1)
        self.enable_a_search = QtWidgets.QRadioButton(self.credentials_tab)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.enable_a_search.setFont(font)
        self.enable_a_search.setChecked(True)
        self.enable_a_search.setObjectName("enable_a_search")
        self.findpatient_layout.addWidget(self.enable_a_search, 2, 0, 1, 1)
        self.gridLayout_5.addLayout(self.findpatient_layout, 0, 0, 1, 1)
        self.patient_table = QtWidgets.QTableView(self.credentials_tab)
        self.patient_table.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.patient_table.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.patient_table.setSortingEnabled(True)
        self.patient_table.setObjectName("patient_table")
        self.gridLayout_5.addWidget(self.patient_table, 0, 1, 1, 1)
        self.tab_widget.addTab(self.credentials_tab, "")
        self.examination_tab = QtWidgets.QWidget()
        self.examination_tab.setObjectName("examination_tab")
        self.gridLayout = QtWidgets.QGridLayout(self.examination_tab)
        self.gridLayout.setObjectName("gridLayout")
        self.examination_table = QtWidgets.QTableView(self.examination_tab)
        self.examination_table.setFrameShadow(QtWidgets.QFrame.Plain)
        self.examination_table.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.examination_table.setSortingEnabled(True)
        self.examination_table.setObjectName("examination_table")
        self.gridLayout.addWidget(self.examination_table, 0, 1, 1, 1)
        self.examination_tab_main_layout = QtWidgets.QGroupBox(self.examination_tab)
        self.examination_tab_main_layout.setMinimumSize(QtCore.QSize(350, 0))
        self.examination_tab_main_layout.setMaximumSize(QtCore.QSize(350, 16777215))
        self.examination_tab_main_layout.setTitle("")
        self.examination_tab_main_layout.setObjectName("examination_tab_main_layout")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.examination_tab_main_layout)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.criteria_box_label = QtWidgets.QLabel(self.examination_tab_main_layout)
        self.criteria_box_label.setMaximumSize(QtCore.QSize(16777215, 15))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.criteria_box_label.setFont(font)
        self.criteria_box_label.setAlignment(QtCore.Qt.AlignCenter)
        self.criteria_box_label.setObjectName("criteria_box_label")
        self.gridLayout_6.addWidget(self.criteria_box_label, 1, 0, 1, 1)
        self.patient_examination_main_label = QtWidgets.QLabel(self.examination_tab_main_layout)
        self.patient_examination_main_label.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.patient_examination_main_label.setFont(font)
        self.patient_examination_main_label.setAlignment(QtCore.Qt.AlignCenter)
        self.patient_examination_main_label.setObjectName("patient_examination_main_label")
        self.gridLayout_6.addWidget(self.patient_examination_main_label, 0, 0, 1, 1)
        self.scrollArea = QtWidgets.QScrollArea(self.examination_tab_main_layout)
        self.scrollArea.setMinimumSize(QtCore.QSize(150, 300))
        self.scrollArea.setMaximumSize(QtCore.QSize(330, 16777215))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 328, 298))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.criteria_container_groupbox = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        self.criteria_container_groupbox.setTitle("")
        self.criteria_container_groupbox.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.criteria_container_groupbox.setObjectName("criteria_container_groupbox")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.criteria_container_groupbox)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout_2.addWidget(self.criteria_container_groupbox, 0, 0, 1, 1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout_6.addWidget(self.scrollArea, 2, 0, 1, 1, QtCore.Qt.AlignTop)
        self.modify_criteria_groupbox = QtWidgets.QGroupBox(self.examination_tab_main_layout)
        self.modify_criteria_groupbox.setMinimumSize(QtCore.QSize(300, 0))
        self.modify_criteria_groupbox.setMaximumSize(QtCore.QSize(16777215, 250))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.modify_criteria_groupbox.setFont(font)
        self.modify_criteria_groupbox.setTitle("")
        self.modify_criteria_groupbox.setObjectName("modify_criteria_groupbox")
        self.A = QtWidgets.QGridLayout(self.modify_criteria_groupbox)
        self.A.setObjectName("A")
        self.criteria_operator_label = QtWidgets.QLabel(self.modify_criteria_groupbox)
        self.criteria_operator_label.setMaximumSize(QtCore.QSize(16777215, 15))
        self.criteria_operator_label.setObjectName("criteria_operator_label")
        self.A.addWidget(self.criteria_operator_label, 4, 2, 1, 1)
        self.criteria_parameter_label = QtWidgets.QLabel(self.modify_criteria_groupbox)
        self.criteria_parameter_label.setMaximumSize(QtCore.QSize(16777215, 15))
        self.criteria_parameter_label.setObjectName("criteria_parameter_label")
        self.A.addWidget(self.criteria_parameter_label, 4, 0, 1, 1)
        self.parameter_le = QtWidgets.QLineEdit(self.modify_criteria_groupbox)
        self.parameter_le.setMaximumSize(QtCore.QSize(90, 16777215))
        self.parameter_le.setObjectName("parameter_le")
        self.A.addWidget(self.parameter_le, 6, 3, 1, 1)
        self.criteria_removal_label = QtWidgets.QLabel(self.modify_criteria_groupbox)
        self.criteria_removal_label.setMaximumSize(QtCore.QSize(16777215, 15))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.criteria_removal_label.setFont(font)
        self.criteria_removal_label.setAlignment(QtCore.Qt.AlignCenter)
        self.criteria_removal_label.setObjectName("criteria_removal_label")
        self.A.addWidget(self.criteria_removal_label, 8, 0, 1, 5)
        self.criteria_removal_le = QtWidgets.QLineEdit(self.modify_criteria_groupbox)
        self.criteria_removal_le.setMaximumSize(QtCore.QSize(80, 16777215))
        self.criteria_removal_le.setObjectName("criteria_removal_le")
        self.A.addWidget(self.criteria_removal_le, 10, 3, 1, 1)
        self.criteria_adding_label = QtWidgets.QLabel(self.modify_criteria_groupbox)
        self.criteria_adding_label.setMaximumSize(QtCore.QSize(16777215, 10))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.criteria_adding_label.setFont(font)
        self.criteria_adding_label.setAlignment(QtCore.Qt.AlignCenter)
        self.criteria_adding_label.setObjectName("criteria_adding_label")
        self.A.addWidget(self.criteria_adding_label, 3, 0, 1, 5)
        self.examination_remove_criteria_button = QtWidgets.QPushButton(self.modify_criteria_groupbox)
        self.examination_remove_criteria_button.setMaximumSize(QtCore.QSize(50, 16777215))
        self.examination_remove_criteria_button.setObjectName("examination_remove_criteria_button")
        self.A.addWidget(self.examination_remove_criteria_button, 10, 4, 1, 1)
        self.line = QtWidgets.QFrame(self.modify_criteria_groupbox)
        self.line.setFrameShadow(QtWidgets.QFrame.Raised)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setObjectName("line")
        self.A.addWidget(self.line, 2, 0, 1, 5)
        self.criteria_modify_label = QtWidgets.QLabel(self.modify_criteria_groupbox)
        self.criteria_modify_label.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.criteria_modify_label.setFont(font)
        self.criteria_modify_label.setAlignment(QtCore.Qt.AlignCenter)
        self.criteria_modify_label.setObjectName("criteria_modify_label")
        self.A.addWidget(self.criteria_modify_label, 1, 0, 1, 5)
        self.examination_search_button = QtWidgets.QPushButton(self.modify_criteria_groupbox)
        self.examination_search_button.setObjectName("examination_search_button")
        self.A.addWidget(self.examination_search_button, 11, 0, 1, 3)
        self.line_2 = QtWidgets.QFrame(self.modify_criteria_groupbox)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.A.addWidget(self.line_2, 7, 0, 1, 5)
        self.export_tabledata_button = QtWidgets.QPushButton(self.modify_criteria_groupbox)
        self.export_tabledata_button.setObjectName("export_tabledata_button")
        self.A.addWidget(self.export_tabledata_button, 12, 3, 1, 1)
        self.criteria_parameter_label_2 = QtWidgets.QLabel(self.modify_criteria_groupbox)
        self.criteria_parameter_label_2.setMaximumSize(QtCore.QSize(16777215, 15))
        self.criteria_parameter_label_2.setObjectName("criteria_parameter_label_2")
        self.A.addWidget(self.criteria_parameter_label_2, 4, 3, 1, 1)
        self.examination_search_reset_button = QtWidgets.QPushButton(self.modify_criteria_groupbox)
        self.examination_search_reset_button.setObjectName("examination_search_reset_button")
        self.A.addWidget(self.examination_search_reset_button, 11, 3, 1, 2)
        self.examination_add_criteria_button = QtWidgets.QPushButton(self.modify_criteria_groupbox)
        self.examination_add_criteria_button.setMaximumSize(QtCore.QSize(50, 16777215))
        self.examination_add_criteria_button.setObjectName("examination_add_criteria_button")
        self.A.addWidget(self.examination_add_criteria_button, 6, 4, 1, 1)
        self.parameter_cb = QtWidgets.QComboBox(self.modify_criteria_groupbox)
        self.parameter_cb.setMinimumSize(QtCore.QSize(120, 0))
        self.parameter_cb.setMaximumSize(QtCore.QSize(120, 16777215))
        self.parameter_cb.setObjectName("parameter_cb")
        self.parameter_cb.addItem("")
        self.parameter_cb.setItemText(0, "")
        self.parameter_cb.addItem("")
        self.parameter_cb.addItem("")
        self.parameter_cb.addItem("")
        self.parameter_cb.addItem("")
        self.parameter_cb.addItem("")
        self.parameter_cb.addItem("")
        self.parameter_cb.addItem("")
        self.parameter_cb.addItem("")
        self.parameter_cb.addItem("")
        self.parameter_cb.addItem("")
        self.A.addWidget(self.parameter_cb, 6, 0, 1, 1)
        self.operator_cb = QtWidgets.QComboBox(self.modify_criteria_groupbox)
        self.operator_cb.setMinimumSize(QtCore.QSize(40, 0))
        self.operator_cb.setMaximumSize(QtCore.QSize(30, 16777215))
        self.operator_cb.setObjectName("operator_cb")
        self.operator_cb.addItem("")
        self.operator_cb.setItemText(0, "")
        self.operator_cb.addItem("")
        self.operator_cb.addItem("")
        self.operator_cb.addItem("")
        self.A.addWidget(self.operator_cb, 6, 2, 1, 1)
        self.gridLayout_6.addWidget(self.modify_criteria_groupbox, 3, 0, 1, 1)
        self.gridLayout.addWidget(self.examination_tab_main_layout, 0, 0, 1, 1)
        self.tab_widget.addTab(self.examination_tab, "")
        self.irregularities_tab = QtWidgets.QWidget()
        self.irregularities_tab.setObjectName("irregularities_tab")
        self.tab_widget.addTab(self.irregularities_tab, "")
        self.statistics_tab = QtWidgets.QWidget()
        self.statistics_tab.setObjectName("statistics_tab")
        self.tab_widget.addTab(self.statistics_tab, "")
        self.gridLayout_4.addWidget(self.tab_widget, 0, 0, 1, 1)
        main_app_window.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(main_app_window)
        self.statusbar.setObjectName("statusbar")
        main_app_window.setStatusBar(self.statusbar)

        self.retranslateUi(main_app_window)
        self.tab_widget.setCurrentIndex(2)
        self.findpatient_tab_widget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(main_app_window)
        main_app_window.setTabOrder(self.name_le, self.surname_le)
        main_app_window.setTabOrder(self.surname_le, self.pesel_le)
        main_app_window.setTabOrder(self.pesel_le, self.dateofbirth_le)
        main_app_window.setTabOrder(self.dateofbirth_le, self.gender_cb)
        main_app_window.setTabOrder(self.gender_cb, self.country_cb)
        main_app_window.setTabOrder(self.country_cb, self.phonenumber_le)
        main_app_window.setTabOrder(self.phonenumber_le, self.city_le)
        main_app_window.setTabOrder(self.city_le, self.postalcode_le)
        main_app_window.setTabOrder(self.postalcode_le, self.findpatient_search_button)
        main_app_window.setTabOrder(self.findpatient_search_button, self.findpatient_showall_button)
        main_app_window.setTabOrder(self.findpatient_showall_button, self.findpatient_tab_widget)
        main_app_window.setTabOrder(self.findpatient_tab_widget, self.examination_table)
        main_app_window.setTabOrder(self.examination_table, self.patient_table)

    def retranslateUi(self, main_app_window):
        _translate = QtCore.QCoreApplication.translate
        main_app_window.setWindowTitle(_translate("main_app_window", "MainWindow"))
        self.label.setText(_translate("main_app_window", "Remote Health Monitoring System Application"))
        self.label_2.setText(_translate("main_app_window", "TextLabel"))
        self.tab_widget.setTabText(self.tab_widget.indexOf(self.general_tab), _translate("main_app_window", "General"))
        self.findpatient_search_button.setText(_translate("main_app_window", "Search"))
        self.findpatient_label.setText(_translate("main_app_window", "Find a patient"))
        self.name_label.setText(_translate("main_app_window", "Name"))
        self.pesel_label.setText(_translate("main_app_window", "PESEL"))
        self.surname_label.setText(_translate("main_app_window", "Surname"))
        self.findpatient_tab_widget.setTabText(self.findpatient_tab_widget.indexOf(self.basic_param_tab), _translate("main_app_window", "Basic Search"))
        self.gender_label.setText(_translate("main_app_window", "Gender"))
        self.city_label.setText(_translate("main_app_window", "City"))
        self.phonenumber_label.setText(_translate("main_app_window", "Phone number"))
        self.postalcode_label.setText(_translate("main_app_window", "Postal code"))
        self.country_cb.setItemText(1, _translate("main_app_window", "Austria"))
        self.country_cb.setItemText(2, _translate("main_app_window", "Czech Republic"))
        self.country_cb.setItemText(3, _translate("main_app_window", "France"))
        self.country_cb.setItemText(4, _translate("main_app_window", "Germany"))
        self.country_cb.setItemText(5, _translate("main_app_window", "Italy"))
        self.country_cb.setItemText(6, _translate("main_app_window", "Poland"))
        self.country_cb.setItemText(7, _translate("main_app_window", "Portugal"))
        self.country_cb.setItemText(8, _translate("main_app_window", "Russia"))
        self.country_cb.setItemText(9, _translate("main_app_window", "Spain"))
        self.country_cb.setItemText(10, _translate("main_app_window", "Uk"))
        self.country_cb.setItemText(11, _translate("main_app_window", "USA"))
        self.country_label.setText(_translate("main_app_window", "Country"))
        self.gender_cb.setItemText(1, _translate("main_app_window", "M"))
        self.gender_cb.setItemText(2, _translate("main_app_window", "F"))
        self.dateofbirth_label.setText(_translate("main_app_window", "Date of birth"))
        self.findpatient_tab_widget.setTabText(self.findpatient_tab_widget.indexOf(self.adv_param_tab), _translate("main_app_window", "Advanced Search"))
        self.findpatient_showall_button.setText(_translate("main_app_window", "Show All"))
        self.enable_a_search.setText(_translate("main_app_window", "Show Many"))
        self.tab_widget.setTabText(self.tab_widget.indexOf(self.credentials_tab), _translate("main_app_window", "Patient Credentials"))
        self.criteria_box_label.setText(_translate("main_app_window", "Selected Criteria"))
        self.patient_examination_main_label.setText(_translate("main_app_window", "Patient Examination"))
        self.criteria_operator_label.setText(_translate("main_app_window", "Operator"))
        self.criteria_parameter_label.setText(_translate("main_app_window", "Parameter"))
        self.criteria_removal_label.setText(_translate("main_app_window", "Remove criteria - Write criteria index"))
        self.criteria_adding_label.setText(_translate("main_app_window", "Add criteria - Choose criteria options"))
        self.examination_remove_criteria_button.setText(_translate("main_app_window", "Remove"))
        self.criteria_modify_label.setText(_translate("main_app_window", "Add or remove criteria"))
        self.examination_search_button.setText(_translate("main_app_window", "Search"))
        self.export_tabledata_button.setText(_translate("main_app_window", "Export"))
        self.criteria_parameter_label_2.setText(_translate("main_app_window", "Parameter Value"))
        self.examination_search_reset_button.setText(_translate("main_app_window", "Reset and show all"))
        self.examination_add_criteria_button.setText(_translate("main_app_window", "Add"))
        self.parameter_cb.setItemText(1, _translate("main_app_window", "Name"))
        self.parameter_cb.setItemText(2, _translate("main_app_window", "Surname"))
        self.parameter_cb.setItemText(3, _translate("main_app_window", "Examination Date"))
        self.parameter_cb.setItemText(4, _translate("main_app_window", "Systolic Pressure"))
        self.parameter_cb.setItemText(5, _translate("main_app_window", "Diastolic Pressure"))
        self.parameter_cb.setItemText(6, _translate("main_app_window", "Heart Rate"))
        self.parameter_cb.setItemText(7, _translate("main_app_window", "Patient Height"))
        self.parameter_cb.setItemText(8, _translate("main_app_window", "Patient Weight"))
        self.parameter_cb.setItemText(9, _translate("main_app_window", "BMI"))
        self.parameter_cb.setItemText(10, _translate("main_app_window", "Parameter Warning"))
        self.operator_cb.setItemText(1, _translate("main_app_window", ">"))
        self.operator_cb.setItemText(2, _translate("main_app_window", "<"))
        self.operator_cb.setItemText(3, _translate("main_app_window", "="))
        self.tab_widget.setTabText(self.tab_widget.indexOf(self.examination_tab), _translate("main_app_window", "Patient Examination"))
        self.tab_widget.setTabText(self.tab_widget.indexOf(self.irregularities_tab), _translate("main_app_window", "Trend"))
        self.tab_widget.setTabText(self.tab_widget.indexOf(self.statistics_tab), _translate("main_app_window", "Statistics"))

