# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ApplicationWindow2.ui'
#
# Created by: PyQt5 UI code generator 5.4.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_main_app_window(object):
    def setupUi(self, main_app_window):
        main_app_window.setObjectName("main_app_window")
        main_app_window.setWindowModality(QtCore.Qt.NonModal)
        main_app_window.resize(951, 630)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(main_app_window.sizePolicy().hasHeightForWidth())
        main_app_window.setSizePolicy(sizePolicy)
        self.centralwidget = QtWidgets.QWidget(main_app_window)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.tab_widget = QtWidgets.QTabWidget(self.centralwidget)
        self.tab_widget.setStyleSheet("")
        self.tab_widget.setObjectName("tab_widget")
        self.general_tab = QtWidgets.QWidget()
        self.general_tab.setObjectName("general_tab")
        self.formLayoutWidget = QtWidgets.QWidget(self.general_tab)
        self.formLayoutWidget.setGeometry(QtCore.QRect(10, 10, 941, 521))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setTextFormat(QtCore.Qt.RichText)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setWordWrap(False)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.label)
        self.tab_widget.addTab(self.general_tab, "")
        self.credentials_tab = QtWidgets.QWidget()
        self.credentials_tab.setObjectName("credentials_tab")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.credentials_tab)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.findpatient_layout = QtWidgets.QGridLayout()
        self.findpatient_layout.setObjectName("findpatient_layout")
        self.findpatient_search_button = QtWidgets.QPushButton(self.credentials_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.findpatient_search_button.sizePolicy().hasHeightForWidth())
        self.findpatient_search_button.setSizePolicy(sizePolicy)
        self.findpatient_search_button.setObjectName("findpatient_search_button")
        self.findpatient_layout.addWidget(self.findpatient_search_button, 4, 0, 1, 1)
        self.findpatient_label = QtWidgets.QLabel(self.credentials_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.findpatient_label.sizePolicy().hasHeightForWidth())
        self.findpatient_label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        self.findpatient_label.setFont(font)
        self.findpatient_label.setAutoFillBackground(False)
        self.findpatient_label.setAlignment(QtCore.Qt.AlignCenter)
        self.findpatient_label.setWordWrap(False)
        self.findpatient_label.setContentsMargins(1, 1, 1, 1)
        self.findpatient_label.setIndent(-1)
        self.findpatient_label.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.findpatient_label.setObjectName("findpatient_label")
        self.findpatient_layout.addWidget(self.findpatient_label, 1, 0, 1, 1)
        self.findpatient_tab_widget = QtWidgets.QTabWidget(self.credentials_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.findpatient_tab_widget.sizePolicy().hasHeightForWidth())
        self.findpatient_tab_widget.setSizePolicy(sizePolicy)
        self.findpatient_tab_widget.setObjectName("findpatient_tab_widget")
        self.basic_param_tab = QtWidgets.QWidget()
        self.basic_param_tab.setObjectName("basic_param_tab")
        self.gridLayoutWidget_6 = QtWidgets.QWidget(self.basic_param_tab)
        self.gridLayoutWidget_6.setGeometry(QtCore.QRect(0, 0, 191, 171))
        self.gridLayoutWidget_6.setObjectName("gridLayoutWidget_6")
        self.findpatient_basic_layout = QtWidgets.QGridLayout(self.gridLayoutWidget_6)
        self.findpatient_basic_layout.setContentsMargins(0, 0, 0, 0)
        self.findpatient_basic_layout.setObjectName("findpatient_basic_layout")
        self.pesel_le = QtWidgets.QLineEdit(self.gridLayoutWidget_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pesel_le.sizePolicy().hasHeightForWidth())
        self.pesel_le.setSizePolicy(sizePolicy)
        self.pesel_le.setObjectName("pesel_le")
        self.findpatient_basic_layout.addWidget(self.pesel_le, 7, 0, 1, 1)
        self.surname_le = QtWidgets.QLineEdit(self.gridLayoutWidget_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.surname_le.sizePolicy().hasHeightForWidth())
        self.surname_le.setSizePolicy(sizePolicy)
        self.surname_le.setObjectName("surname_le")
        self.findpatient_basic_layout.addWidget(self.surname_le, 4, 0, 1, 1)
        self.name_label = QtWidgets.QLabel(self.gridLayoutWidget_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.name_label.sizePolicy().hasHeightForWidth())
        self.name_label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.name_label.setFont(font)
        self.name_label.setAlignment(QtCore.Qt.AlignCenter)
        self.name_label.setObjectName("name_label")
        self.findpatient_basic_layout.addWidget(self.name_label, 0, 0, 1, 1)
        self.name_le = QtWidgets.QLineEdit(self.gridLayoutWidget_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.name_le.sizePolicy().hasHeightForWidth())
        self.name_le.setSizePolicy(sizePolicy)
        self.name_le.setObjectName("name_le")
        self.findpatient_basic_layout.addWidget(self.name_le, 1, 0, 1, 1)
        self.pesel_label = QtWidgets.QLabel(self.gridLayoutWidget_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pesel_label.sizePolicy().hasHeightForWidth())
        self.pesel_label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pesel_label.setFont(font)
        self.pesel_label.setAlignment(QtCore.Qt.AlignCenter)
        self.pesel_label.setObjectName("pesel_label")
        self.findpatient_basic_layout.addWidget(self.pesel_label, 5, 0, 1, 1)
        self.surname_label = QtWidgets.QLabel(self.gridLayoutWidget_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.surname_label.sizePolicy().hasHeightForWidth())
        self.surname_label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.surname_label.setFont(font)
        self.surname_label.setAutoFillBackground(False)
        self.surname_label.setTextFormat(QtCore.Qt.AutoText)
        self.surname_label.setScaledContents(False)
        self.surname_label.setAlignment(QtCore.Qt.AlignCenter)
        self.surname_label.setObjectName("surname_label")
        self.findpatient_basic_layout.addWidget(self.surname_label, 2, 0, 1, 1)
        self.findpatient_tab_widget.addTab(self.basic_param_tab, "")
        self.adv_param_tab = QtWidgets.QWidget()
        self.adv_param_tab.setObjectName("adv_param_tab")
        self.gridLayoutWidget_5 = QtWidgets.QWidget(self.adv_param_tab)
        self.gridLayoutWidget_5.setGeometry(QtCore.QRect(0, 0, 191, 314))
        self.gridLayoutWidget_5.setObjectName("gridLayoutWidget_5")
        self.findpatient_adv_layout = QtWidgets.QGridLayout(self.gridLayoutWidget_5)
        self.findpatient_adv_layout.setContentsMargins(0, 0, 0, 0)
        self.findpatient_adv_layout.setObjectName("findpatient_adv_layout")
        self.gender_label = QtWidgets.QLabel(self.gridLayoutWidget_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gender_label.sizePolicy().hasHeightForWidth())
        self.gender_label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.gender_label.setFont(font)
        self.gender_label.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.gender_label.setObjectName("gender_label")
        self.findpatient_adv_layout.addWidget(self.gender_label, 2, 0, 1, 1)
        self.city_label = QtWidgets.QLabel(self.gridLayoutWidget_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.city_label.sizePolicy().hasHeightForWidth())
        self.city_label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.city_label.setFont(font)
        self.city_label.setAlignment(QtCore.Qt.AlignCenter)
        self.city_label.setObjectName("city_label")
        self.findpatient_adv_layout.addWidget(self.city_label, 8, 0, 1, 1)
        self.phonenumber_label = QtWidgets.QLabel(self.gridLayoutWidget_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.phonenumber_label.sizePolicy().hasHeightForWidth())
        self.phonenumber_label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.phonenumber_label.setFont(font)
        self.phonenumber_label.setAlignment(QtCore.Qt.AlignCenter)
        self.phonenumber_label.setObjectName("phonenumber_label")
        self.findpatient_adv_layout.addWidget(self.phonenumber_label, 6, 0, 1, 1)
        self.phonenumber_le = QtWidgets.QLineEdit(self.gridLayoutWidget_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.phonenumber_le.sizePolicy().hasHeightForWidth())
        self.phonenumber_le.setSizePolicy(sizePolicy)
        self.phonenumber_le.setObjectName("phonenumber_le")
        self.findpatient_adv_layout.addWidget(self.phonenumber_le, 7, 0, 1, 1)
        self.postalcode_label = QtWidgets.QLabel(self.gridLayoutWidget_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.postalcode_label.sizePolicy().hasHeightForWidth())
        self.postalcode_label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.postalcode_label.setFont(font)
        self.postalcode_label.setAlignment(QtCore.Qt.AlignCenter)
        self.postalcode_label.setObjectName("postalcode_label")
        self.findpatient_adv_layout.addWidget(self.postalcode_label, 10, 0, 1, 1)
        self.city_le = QtWidgets.QLineEdit(self.gridLayoutWidget_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.city_le.sizePolicy().hasHeightForWidth())
        self.city_le.setSizePolicy(sizePolicy)
        self.city_le.setObjectName("city_le")
        self.findpatient_adv_layout.addWidget(self.city_le, 9, 0, 1, 1)
        self.country_cb = QtWidgets.QComboBox(self.gridLayoutWidget_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.country_cb.sizePolicy().hasHeightForWidth())
        self.country_cb.setSizePolicy(sizePolicy)
        self.country_cb.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContents)
        self.country_cb.setObjectName("country_cb")
        self.country_cb.addItem("")
        self.country_cb.setItemText(0, "")
        self.country_cb.addItem("")
        self.country_cb.addItem("")
        self.country_cb.addItem("")
        self.country_cb.addItem("")
        self.country_cb.addItem("")
        self.country_cb.addItem("")
        self.country_cb.addItem("")
        self.country_cb.addItem("")
        self.country_cb.addItem("")
        self.country_cb.addItem("")
        self.country_cb.addItem("")
        self.findpatient_adv_layout.addWidget(self.country_cb, 5, 0, 1, 1)
        self.country_label = QtWidgets.QLabel(self.gridLayoutWidget_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.country_label.sizePolicy().hasHeightForWidth())
        self.country_label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.country_label.setFont(font)
        self.country_label.setAlignment(QtCore.Qt.AlignCenter)
        self.country_label.setObjectName("country_label")
        self.findpatient_adv_layout.addWidget(self.country_label, 4, 0, 1, 1)
        self.postalcode_le = QtWidgets.QLineEdit(self.gridLayoutWidget_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.postalcode_le.sizePolicy().hasHeightForWidth())
        self.postalcode_le.setSizePolicy(sizePolicy)
        self.postalcode_le.setObjectName("postalcode_le")
        self.findpatient_adv_layout.addWidget(self.postalcode_le, 11, 0, 1, 1)
        self.gender_cb = QtWidgets.QComboBox(self.gridLayoutWidget_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gender_cb.sizePolicy().hasHeightForWidth())
        self.gender_cb.setSizePolicy(sizePolicy)
        self.gender_cb.setObjectName("gender_cb")
        self.gender_cb.addItem("")
        self.gender_cb.setItemText(0, "")
        self.gender_cb.addItem("")
        self.gender_cb.addItem("")
        self.findpatient_adv_layout.addWidget(self.gender_cb, 3, 0, 1, 1)
        self.dateofbirth_label = QtWidgets.QLabel(self.gridLayoutWidget_5)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.dateofbirth_label.setFont(font)
        self.dateofbirth_label.setAlignment(QtCore.Qt.AlignCenter)
        self.dateofbirth_label.setObjectName("dateofbirth_label")
        self.findpatient_adv_layout.addWidget(self.dateofbirth_label, 0, 0, 1, 1)
        self.dateofbirth_le = QtWidgets.QLineEdit(self.gridLayoutWidget_5)
        self.dateofbirth_le.setObjectName("dateofbirth_le")
        self.findpatient_adv_layout.addWidget(self.dateofbirth_le, 1, 0, 1, 1)
        self.findpatient_tab_widget.addTab(self.adv_param_tab, "")
        self.findpatient_layout.addWidget(self.findpatient_tab_widget, 3, 0, 1, 1)
        self.findpatient_showall_button = QtWidgets.QPushButton(self.credentials_tab)
        self.findpatient_showall_button.setObjectName("findpatient_showall_button")
        self.findpatient_layout.addWidget(self.findpatient_showall_button, 5, 0, 1, 1)
        self.enable_a_search = QtWidgets.QRadioButton(self.credentials_tab)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.enable_a_search.setFont(font)
        self.enable_a_search.setChecked(True)
        self.enable_a_search.setObjectName("enable_a_search")
        self.findpatient_layout.addWidget(self.enable_a_search, 2, 0, 1, 1)
        self.gridLayout_5.addLayout(self.findpatient_layout, 0, 0, 1, 1)
        self.patient_table = QtWidgets.QTableView(self.credentials_tab)
        self.patient_table.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.patient_table.setSortingEnabled(True)
        self.patient_table.setObjectName("patient_table")
        self.gridLayout_5.addWidget(self.patient_table, 0, 1, 1, 1)
        self.tab_widget.addTab(self.credentials_tab, "")
        self.examination_tab = QtWidgets.QWidget()
        self.examination_tab.setObjectName("examination_tab")
        self.examination_params_scrollarea = QtWidgets.QScrollArea(self.examination_tab)
        self.examination_params_scrollarea.setGeometry(QtCore.QRect(0, 440, 931, 131))
        self.examination_params_scrollarea.setWidgetResizable(True)
        self.examination_params_scrollarea.setObjectName("examination_params_scrollarea")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 912, 277))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents_2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout_6 = QtWidgets.QGridLayout()
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.comboBox_5 = QtWidgets.QComboBox(self.scrollAreaWidgetContents_2)
        self.comboBox_5.setObjectName("comboBox_5")
        self.gridLayout_6.addWidget(self.comboBox_5, 6, 2, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label_4.setObjectName("label_4")
        self.gridLayout_6.addWidget(self.label_4, 3, 1, 1, 1)
        self.checkBox_10 = QtWidgets.QCheckBox(self.scrollAreaWidgetContents_2)
        self.checkBox_10.setText("")
        self.checkBox_10.setObjectName("checkBox_10")
        self.gridLayout_6.addWidget(self.checkBox_10, 9, 0, 1, 1)
        self.comboBox_7 = QtWidgets.QComboBox(self.scrollAreaWidgetContents_2)
        self.comboBox_7.setObjectName("comboBox_7")
        self.gridLayout_6.addWidget(self.comboBox_7, 8, 2, 1, 1)
        self.comboBox_9 = QtWidgets.QComboBox(self.scrollAreaWidgetContents_2)
        self.comboBox_9.setObjectName("comboBox_9")
        self.gridLayout_6.addWidget(self.comboBox_9, 10, 2, 1, 1)
        self.checkBox_8 = QtWidgets.QCheckBox(self.scrollAreaWidgetContents_2)
        self.checkBox_8.setText("")
        self.checkBox_8.setObjectName("checkBox_8")
        self.gridLayout_6.addWidget(self.checkBox_8, 7, 0, 1, 1)
        self.checkBox_2 = QtWidgets.QCheckBox(self.scrollAreaWidgetContents_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBox_2.sizePolicy().hasHeightForWidth())
        self.checkBox_2.setSizePolicy(sizePolicy)
        self.checkBox_2.setText("")
        self.checkBox_2.setObjectName("checkBox_2")
        self.gridLayout_6.addWidget(self.checkBox_2, 2, 0, 1, 1)
        self.checkBox_11 = QtWidgets.QCheckBox(self.scrollAreaWidgetContents_2)
        self.checkBox_11.setText("")
        self.checkBox_11.setObjectName("checkBox_11")
        self.gridLayout_6.addWidget(self.checkBox_11, 10, 0, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label_9.setObjectName("label_9")
        self.gridLayout_6.addWidget(self.label_9, 8, 1, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label_10.setObjectName("label_10")
        self.gridLayout_6.addWidget(self.label_10, 9, 1, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label_11.setObjectName("label_11")
        self.gridLayout_6.addWidget(self.label_11, 10, 1, 1, 1)
        self.checkBox_5 = QtWidgets.QCheckBox(self.scrollAreaWidgetContents_2)
        self.checkBox_5.setText("")
        self.checkBox_5.setObjectName("checkBox_5")
        self.gridLayout_6.addWidget(self.checkBox_5, 4, 0, 1, 1)
        self.checkBox_6 = QtWidgets.QCheckBox(self.scrollAreaWidgetContents_2)
        self.checkBox_6.setText("")
        self.checkBox_6.setObjectName("checkBox_6")
        self.gridLayout_6.addWidget(self.checkBox_6, 5, 0, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label_8.setObjectName("label_8")
        self.gridLayout_6.addWidget(self.label_8, 7, 1, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label_7.setObjectName("label_7")
        self.gridLayout_6.addWidget(self.label_7, 6, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout_6.addWidget(self.label_2, 0, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label_6.setObjectName("label_6")
        self.gridLayout_6.addWidget(self.label_6, 5, 1, 1, 1)
        self.comboBox_6 = QtWidgets.QComboBox(self.scrollAreaWidgetContents_2)
        self.comboBox_6.setObjectName("comboBox_6")
        self.gridLayout_6.addWidget(self.comboBox_6, 7, 2, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label_5.setObjectName("label_5")
        self.gridLayout_6.addWidget(self.label_5, 4, 1, 1, 1)
        self.comboBox_8 = QtWidgets.QComboBox(self.scrollAreaWidgetContents_2)
        self.comboBox_8.setObjectName("comboBox_8")
        self.gridLayout_6.addWidget(self.comboBox_8, 9, 2, 1, 1)
        self.parameter1operator_cb = QtWidgets.QComboBox(self.scrollAreaWidgetContents_2)
        self.parameter1operator_cb.setObjectName("parameter1operator_cb")
        self.parameter1operator_cb.addItem("")
        self.parameter1operator_cb.setItemText(0, "")
        self.parameter1operator_cb.addItem("")
        self.parameter1operator_cb.addItem("")
        self.parameter1operator_cb.addItem("")
        self.gridLayout_6.addWidget(self.parameter1operator_cb, 2, 2, 1, 1)
        self.comboBox_2 = QtWidgets.QComboBox(self.scrollAreaWidgetContents_2)
        self.comboBox_2.setObjectName("comboBox_2")
        self.gridLayout_6.addWidget(self.comboBox_2, 3, 2, 1, 1)
        self.checkBox_3 = QtWidgets.QCheckBox(self.scrollAreaWidgetContents_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBox_3.sizePolicy().hasHeightForWidth())
        self.checkBox_3.setSizePolicy(sizePolicy)
        self.checkBox_3.setText("")
        self.checkBox_3.setObjectName("checkBox_3")
        self.gridLayout_6.addWidget(self.checkBox_3, 3, 0, 1, 1)
        self.parameter1_le = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_2)
        self.parameter1_le.setObjectName("parameter1_le")
        self.gridLayout_6.addWidget(self.parameter1_le, 2, 3, 1, 1)
        self.comboBox_3 = QtWidgets.QComboBox(self.scrollAreaWidgetContents_2)
        self.comboBox_3.setObjectName("comboBox_3")
        self.gridLayout_6.addWidget(self.comboBox_3, 4, 2, 1, 1)
        self.comboBox_4 = QtWidgets.QComboBox(self.scrollAreaWidgetContents_2)
        self.comboBox_4.setObjectName("comboBox_4")
        self.gridLayout_6.addWidget(self.comboBox_4, 5, 2, 1, 1)
        self.checkBox_9 = QtWidgets.QCheckBox(self.scrollAreaWidgetContents_2)
        self.checkBox_9.setText("")
        self.checkBox_9.setObjectName("checkBox_9")
        self.gridLayout_6.addWidget(self.checkBox_9, 8, 0, 1, 1)
        self.checkBox_7 = QtWidgets.QCheckBox(self.scrollAreaWidgetContents_2)
        self.checkBox_7.setText("")
        self.checkBox_7.setObjectName("checkBox_7")
        self.gridLayout_6.addWidget(self.checkBox_7, 6, 0, 1, 1)
        self.examination_search_button = QtWidgets.QPushButton(self.scrollAreaWidgetContents_2)
        self.examination_search_button.setObjectName("examination_search_button")
        self.gridLayout_6.addWidget(self.examination_search_button, 0, 1, 1, 2)
        self.parameter1_cb = QtWidgets.QComboBox(self.scrollAreaWidgetContents_2)
        self.parameter1_cb.setObjectName("parameter1_cb")
        self.parameter1_cb.addItem("")
        self.parameter1_cb.setItemText(0, "")
        self.parameter1_cb.addItem("")
        self.parameter1_cb.addItem("")
        self.parameter1_cb.addItem("")
        self.parameter1_cb.addItem("")
        self.parameter1_cb.addItem("")
        self.parameter1_cb.addItem("")
        self.parameter1_cb.addItem("")
        self.parameter1_cb.addItem("")
        self.parameter1_cb.addItem("")
        self.parameter1_cb.addItem("")
        self.gridLayout_6.addWidget(self.parameter1_cb, 2, 1, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout_6, 0, 0, 1, 1)
        self.examination_params_scrollarea.setWidget(self.scrollAreaWidgetContents_2)
        self.examination_table = QtWidgets.QTableView(self.examination_tab)
        self.examination_table.setGeometry(QtCore.QRect(0, 10, 971, 421))
        self.examination_table.setObjectName("examination_table")
        self.tab_widget.addTab(self.examination_tab, "")
        self.irregularities_tab = QtWidgets.QWidget()
        self.irregularities_tab.setObjectName("irregularities_tab")
        self.tab_widget.addTab(self.irregularities_tab, "")
        self.statistics_tab = QtWidgets.QWidget()
        self.statistics_tab.setObjectName("statistics_tab")
        self.tab_widget.addTab(self.statistics_tab, "")
        self.gridLayout_4.addWidget(self.tab_widget, 0, 0, 1, 1)
        main_app_window.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(main_app_window)
        self.statusbar.setObjectName("statusbar")
        main_app_window.setStatusBar(self.statusbar)

        self.retranslateUi(main_app_window)
        self.tab_widget.setCurrentIndex(1)
        self.findpatient_tab_widget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(main_app_window)
        main_app_window.setTabOrder(self.name_le, self.surname_le)
        main_app_window.setTabOrder(self.surname_le, self.pesel_le)
        main_app_window.setTabOrder(self.pesel_le, self.dateofbirth_le)
        main_app_window.setTabOrder(self.dateofbirth_le, self.gender_cb)
        main_app_window.setTabOrder(self.gender_cb, self.country_cb)
        main_app_window.setTabOrder(self.country_cb, self.phonenumber_le)
        main_app_window.setTabOrder(self.phonenumber_le, self.city_le)
        main_app_window.setTabOrder(self.city_le, self.postalcode_le)
        main_app_window.setTabOrder(self.postalcode_le, self.findpatient_search_button)
        main_app_window.setTabOrder(self.findpatient_search_button, self.findpatient_showall_button)
        main_app_window.setTabOrder(self.findpatient_showall_button, self.examination_params_scrollarea)
        main_app_window.setTabOrder(self.examination_params_scrollarea, self.comboBox_8)
        main_app_window.setTabOrder(self.comboBox_8, self.comboBox_7)
        main_app_window.setTabOrder(self.comboBox_7, self.comboBox_6)
        main_app_window.setTabOrder(self.comboBox_6, self.checkBox_11)
        main_app_window.setTabOrder(self.checkBox_11, self.checkBox_8)
        main_app_window.setTabOrder(self.checkBox_8, self.comboBox_9)
        main_app_window.setTabOrder(self.comboBox_9, self.comboBox_5)
        main_app_window.setTabOrder(self.comboBox_5, self.findpatient_tab_widget)
        main_app_window.setTabOrder(self.findpatient_tab_widget, self.tab_widget)
        main_app_window.setTabOrder(self.tab_widget, self.checkBox_2)
        main_app_window.setTabOrder(self.checkBox_2, self.checkBox_5)
        main_app_window.setTabOrder(self.checkBox_5, self.checkBox_6)
        main_app_window.setTabOrder(self.checkBox_6, self.checkBox_9)
        main_app_window.setTabOrder(self.checkBox_9, self.checkBox_3)
        main_app_window.setTabOrder(self.checkBox_3, self.parameter1operator_cb)
        main_app_window.setTabOrder(self.parameter1operator_cb, self.comboBox_2)
        main_app_window.setTabOrder(self.comboBox_2, self.comboBox_3)
        main_app_window.setTabOrder(self.comboBox_3, self.comboBox_4)
        main_app_window.setTabOrder(self.comboBox_4, self.checkBox_7)
        main_app_window.setTabOrder(self.checkBox_7, self.parameter1_le)
        main_app_window.setTabOrder(self.parameter1_le, self.examination_table)
        main_app_window.setTabOrder(self.examination_table, self.patient_table)
        main_app_window.setTabOrder(self.patient_table, self.checkBox_10)

    def retranslateUi(self, main_app_window):
        _translate = QtCore.QCoreApplication.translate
        main_app_window.setWindowTitle(_translate("main_app_window", "MainWindow"))
        self.label.setText(_translate("main_app_window", "Remote Health Monitoring System Application"))
        self.tab_widget.setTabText(self.tab_widget.indexOf(self.general_tab), _translate("main_app_window", "General"))
        self.findpatient_search_button.setText(_translate("main_app_window", "Search"))
        self.findpatient_label.setText(_translate("main_app_window", "Find a patient"))
        self.name_label.setText(_translate("main_app_window", "Name"))
        self.pesel_label.setText(_translate("main_app_window", "PESEL"))
        self.surname_label.setText(_translate("main_app_window", "Surname"))
        self.findpatient_tab_widget.setTabText(self.findpatient_tab_widget.indexOf(self.basic_param_tab), _translate("main_app_window", "Basic Search"))
        self.gender_label.setText(_translate("main_app_window", "Gender"))
        self.city_label.setText(_translate("main_app_window", "City"))
        self.phonenumber_label.setText(_translate("main_app_window", "Phone number"))
        self.postalcode_label.setText(_translate("main_app_window", "Postal code"))
        self.country_cb.setItemText(1, _translate("main_app_window", "Austria"))
        self.country_cb.setItemText(2, _translate("main_app_window", "Czech Republic"))
        self.country_cb.setItemText(3, _translate("main_app_window", "France"))
        self.country_cb.setItemText(4, _translate("main_app_window", "Germany"))
        self.country_cb.setItemText(5, _translate("main_app_window", "Italy"))
        self.country_cb.setItemText(6, _translate("main_app_window", "Poland"))
        self.country_cb.setItemText(7, _translate("main_app_window", "Portugal"))
        self.country_cb.setItemText(8, _translate("main_app_window", "Russia"))
        self.country_cb.setItemText(9, _translate("main_app_window", "Spain"))
        self.country_cb.setItemText(10, _translate("main_app_window", "Uk"))
        self.country_cb.setItemText(11, _translate("main_app_window", "USA"))
        self.country_label.setText(_translate("main_app_window", "Country"))
        self.gender_cb.setItemText(1, _translate("main_app_window", "M"))
        self.gender_cb.setItemText(2, _translate("main_app_window", "F"))
        self.dateofbirth_label.setText(_translate("main_app_window", "Date of birth"))
        self.findpatient_tab_widget.setTabText(self.findpatient_tab_widget.indexOf(self.adv_param_tab), _translate("main_app_window", "Advanced Search"))
        self.findpatient_showall_button.setText(_translate("main_app_window", "Show All"))
        self.enable_a_search.setText(_translate("main_app_window", "Show Many"))
        self.tab_widget.setTabText(self.tab_widget.indexOf(self.credentials_tab), _translate("main_app_window", "Patient Credentials"))
        self.label_4.setText(_translate("main_app_window", "TextLabel"))
        self.label_9.setText(_translate("main_app_window", "TextLabel"))
        self.label_10.setText(_translate("main_app_window", "TextLabel"))
        self.label_11.setText(_translate("main_app_window", "TextLabel"))
        self.label_8.setText(_translate("main_app_window", "TextLabel"))
        self.label_7.setText(_translate("main_app_window", "TextLabel"))
        self.label_2.setText(_translate("main_app_window", " Enable"))
        self.label_6.setText(_translate("main_app_window", "TextLabel"))
        self.label_5.setText(_translate("main_app_window", "TextLabel"))
        self.parameter1operator_cb.setItemText(1, _translate("main_app_window", ">"))
        self.parameter1operator_cb.setItemText(2, _translate("main_app_window", "<"))
        self.parameter1operator_cb.setItemText(3, _translate("main_app_window", "="))
        self.examination_search_button.setText(_translate("main_app_window", "Search"))
        self.parameter1_cb.setItemText(1, _translate("main_app_window", "Name"))
        self.parameter1_cb.setItemText(2, _translate("main_app_window", "Surname"))
        self.parameter1_cb.setItemText(3, _translate("main_app_window", "Examination Date"))
        self.parameter1_cb.setItemText(4, _translate("main_app_window", "Systolic Pressure"))
        self.parameter1_cb.setItemText(5, _translate("main_app_window", "Diastolic Pressure"))
        self.parameter1_cb.setItemText(6, _translate("main_app_window", "Heart Rate"))
        self.parameter1_cb.setItemText(7, _translate("main_app_window", "Patient Height"))
        self.parameter1_cb.setItemText(8, _translate("main_app_window", "Patient Weight"))
        self.parameter1_cb.setItemText(9, _translate("main_app_window", "BMI"))
        self.parameter1_cb.setItemText(10, _translate("main_app_window", "Parameter Warning"))
        self.tab_widget.setTabText(self.tab_widget.indexOf(self.examination_tab), _translate("main_app_window", "Patient Examination"))
        self.tab_widget.setTabText(self.tab_widget.indexOf(self.irregularities_tab), _translate("main_app_window", "Irregularities"))
        self.tab_widget.setTabText(self.tab_widget.indexOf(self.statistics_tab), _translate("main_app_window", "Statistics"))

