# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ApplicationWindow2.ui'
#
# Created by: PyQt5 UI code generator 5.4.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_main_app_window(object):
    def setupUi(self, main_app_window):
        main_app_window.setObjectName("main_app_window")
        main_app_window.setWindowModality(QtCore.Qt.NonModal)
        main_app_window.resize(920, 740)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(main_app_window.sizePolicy().hasHeightForWidth())
        main_app_window.setSizePolicy(sizePolicy)
        self.centralwidget = QtWidgets.QWidget(main_app_window)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.tab_widget = QtWidgets.QTabWidget(self.centralwidget)
        self.tab_widget.setStyleSheet("")
        self.tab_widget.setObjectName("tab_widget")
        self.general_tab = QtWidgets.QWidget()
        self.general_tab.setObjectName("general_tab")
        self.formLayoutWidget = QtWidgets.QWidget(self.general_tab)
        self.formLayoutWidget.setGeometry(QtCore.QRect(10, 10, 941, 521))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setTextFormat(QtCore.Qt.RichText)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setWordWrap(False)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.label)
        self.tab_widget.addTab(self.general_tab, "")
        self.credentials_tab = QtWidgets.QWidget()
        self.credentials_tab.setObjectName("credentials_tab")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.credentials_tab)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.findpatient_layout = QtWidgets.QGridLayout()
        self.findpatient_layout.setObjectName("findpatient_layout")
        self.findpatient_search_button = QtWidgets.QPushButton(self.credentials_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.findpatient_search_button.sizePolicy().hasHeightForWidth())
        self.findpatient_search_button.setSizePolicy(sizePolicy)
        self.findpatient_search_button.setObjectName("findpatient_search_button")
        self.findpatient_layout.addWidget(self.findpatient_search_button, 4, 0, 1, 1)
        self.findpatient_label = QtWidgets.QLabel(self.credentials_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.findpatient_label.sizePolicy().hasHeightForWidth())
        self.findpatient_label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        self.findpatient_label.setFont(font)
        self.findpatient_label.setAutoFillBackground(False)
        self.findpatient_label.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.findpatient_label.setFrameShadow(QtWidgets.QFrame.Raised)
        self.findpatient_label.setLineWidth(4)
        self.findpatient_label.setMidLineWidth(2)
        self.findpatient_label.setAlignment(QtCore.Qt.AlignCenter)
        self.findpatient_label.setWordWrap(False)
        self.findpatient_label.setContentsMargins(1, 1, 1, 1)
        self.findpatient_label.setIndent(-1)
        self.findpatient_label.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.findpatient_label.setObjectName("findpatient_label")
        self.findpatient_layout.addWidget(self.findpatient_label, 1, 0, 1, 1)
        self.findpatient_tab_widget = QtWidgets.QTabWidget(self.credentials_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.findpatient_tab_widget.sizePolicy().hasHeightForWidth())
        self.findpatient_tab_widget.setSizePolicy(sizePolicy)
        self.findpatient_tab_widget.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.findpatient_tab_widget.setElideMode(QtCore.Qt.ElideLeft)
        self.findpatient_tab_widget.setObjectName("findpatient_tab_widget")
        self.basic_param_tab = QtWidgets.QWidget()
        self.basic_param_tab.setObjectName("basic_param_tab")
        self.gridLayoutWidget_6 = QtWidgets.QWidget(self.basic_param_tab)
        self.gridLayoutWidget_6.setGeometry(QtCore.QRect(0, 0, 191, 171))
        self.gridLayoutWidget_6.setObjectName("gridLayoutWidget_6")
        self.findpatient_basic_layout = QtWidgets.QGridLayout(self.gridLayoutWidget_6)
        self.findpatient_basic_layout.setContentsMargins(0, 0, 0, 0)
        self.findpatient_basic_layout.setObjectName("findpatient_basic_layout")
        self.pesel_le = QtWidgets.QLineEdit(self.gridLayoutWidget_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pesel_le.sizePolicy().hasHeightForWidth())
        self.pesel_le.setSizePolicy(sizePolicy)
        self.pesel_le.setObjectName("pesel_le")
        self.findpatient_basic_layout.addWidget(self.pesel_le, 7, 0, 1, 1)
        self.surname_le = QtWidgets.QLineEdit(self.gridLayoutWidget_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.surname_le.sizePolicy().hasHeightForWidth())
        self.surname_le.setSizePolicy(sizePolicy)
        self.surname_le.setObjectName("surname_le")
        self.findpatient_basic_layout.addWidget(self.surname_le, 4, 0, 1, 1)
        self.name_label = QtWidgets.QLabel(self.gridLayoutWidget_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.name_label.sizePolicy().hasHeightForWidth())
        self.name_label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.name_label.setFont(font)
        self.name_label.setAlignment(QtCore.Qt.AlignCenter)
        self.name_label.setObjectName("name_label")
        self.findpatient_basic_layout.addWidget(self.name_label, 0, 0, 1, 1)
        self.name_le = QtWidgets.QLineEdit(self.gridLayoutWidget_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.name_le.sizePolicy().hasHeightForWidth())
        self.name_le.setSizePolicy(sizePolicy)
        self.name_le.setObjectName("name_le")
        self.findpatient_basic_layout.addWidget(self.name_le, 1, 0, 1, 1)
        self.pesel_label = QtWidgets.QLabel(self.gridLayoutWidget_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pesel_label.sizePolicy().hasHeightForWidth())
        self.pesel_label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pesel_label.setFont(font)
        self.pesel_label.setAlignment(QtCore.Qt.AlignCenter)
        self.pesel_label.setObjectName("pesel_label")
        self.findpatient_basic_layout.addWidget(self.pesel_label, 5, 0, 1, 1)
        self.surname_label = QtWidgets.QLabel(self.gridLayoutWidget_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.surname_label.sizePolicy().hasHeightForWidth())
        self.surname_label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.surname_label.setFont(font)
        self.surname_label.setAutoFillBackground(False)
        self.surname_label.setTextFormat(QtCore.Qt.AutoText)
        self.surname_label.setScaledContents(False)
        self.surname_label.setAlignment(QtCore.Qt.AlignCenter)
        self.surname_label.setObjectName("surname_label")
        self.findpatient_basic_layout.addWidget(self.surname_label, 2, 0, 1, 1)
        self.findpatient_tab_widget.addTab(self.basic_param_tab, "")
        self.adv_param_tab = QtWidgets.QWidget()
        self.adv_param_tab.setObjectName("adv_param_tab")
        self.gridLayoutWidget_5 = QtWidgets.QWidget(self.adv_param_tab)
        self.gridLayoutWidget_5.setGeometry(QtCore.QRect(0, 0, 191, 314))
        self.gridLayoutWidget_5.setObjectName("gridLayoutWidget_5")
        self.findpatient_adv_layout = QtWidgets.QGridLayout(self.gridLayoutWidget_5)
        self.findpatient_adv_layout.setContentsMargins(0, 0, 0, 0)
        self.findpatient_adv_layout.setObjectName("findpatient_adv_layout")
        self.gender_label = QtWidgets.QLabel(self.gridLayoutWidget_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gender_label.sizePolicy().hasHeightForWidth())
        self.gender_label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.gender_label.setFont(font)
        self.gender_label.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.gender_label.setObjectName("gender_label")
        self.findpatient_adv_layout.addWidget(self.gender_label, 2, 0, 1, 1)
        self.city_label = QtWidgets.QLabel(self.gridLayoutWidget_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.city_label.sizePolicy().hasHeightForWidth())
        self.city_label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.city_label.setFont(font)
        self.city_label.setAlignment(QtCore.Qt.AlignCenter)
        self.city_label.setObjectName("city_label")
        self.findpatient_adv_layout.addWidget(self.city_label, 8, 0, 1, 1)
        self.phonenumber_label = QtWidgets.QLabel(self.gridLayoutWidget_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.phonenumber_label.sizePolicy().hasHeightForWidth())
        self.phonenumber_label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.phonenumber_label.setFont(font)
        self.phonenumber_label.setAlignment(QtCore.Qt.AlignCenter)
        self.phonenumber_label.setObjectName("phonenumber_label")
        self.findpatient_adv_layout.addWidget(self.phonenumber_label, 6, 0, 1, 1)
        self.phonenumber_le = QtWidgets.QLineEdit(self.gridLayoutWidget_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.phonenumber_le.sizePolicy().hasHeightForWidth())
        self.phonenumber_le.setSizePolicy(sizePolicy)
        self.phonenumber_le.setObjectName("phonenumber_le")
        self.findpatient_adv_layout.addWidget(self.phonenumber_le, 7, 0, 1, 1)
        self.postalcode_label = QtWidgets.QLabel(self.gridLayoutWidget_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.postalcode_label.sizePolicy().hasHeightForWidth())
        self.postalcode_label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.postalcode_label.setFont(font)
        self.postalcode_label.setAlignment(QtCore.Qt.AlignCenter)
        self.postalcode_label.setObjectName("postalcode_label")
        self.findpatient_adv_layout.addWidget(self.postalcode_label, 10, 0, 1, 1)
        self.city_le = QtWidgets.QLineEdit(self.gridLayoutWidget_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.city_le.sizePolicy().hasHeightForWidth())
        self.city_le.setSizePolicy(sizePolicy)
        self.city_le.setObjectName("city_le")
        self.findpatient_adv_layout.addWidget(self.city_le, 9, 0, 1, 1)
        self.country_cb = QtWidgets.QComboBox(self.gridLayoutWidget_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.country_cb.sizePolicy().hasHeightForWidth())
        self.country_cb.setSizePolicy(sizePolicy)
        self.country_cb.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContents)
        self.country_cb.setObjectName("country_cb")
        self.country_cb.addItem("")
        self.country_cb.setItemText(0, "")
        self.country_cb.addItem("")
        self.country_cb.addItem("")
        self.country_cb.addItem("")
        self.country_cb.addItem("")
        self.country_cb.addItem("")
        self.country_cb.addItem("")
        self.country_cb.addItem("")
        self.country_cb.addItem("")
        self.country_cb.addItem("")
        self.country_cb.addItem("")
        self.country_cb.addItem("")
        self.findpatient_adv_layout.addWidget(self.country_cb, 5, 0, 1, 1)
        self.country_label = QtWidgets.QLabel(self.gridLayoutWidget_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.country_label.sizePolicy().hasHeightForWidth())
        self.country_label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.country_label.setFont(font)
        self.country_label.setAlignment(QtCore.Qt.AlignCenter)
        self.country_label.setObjectName("country_label")
        self.findpatient_adv_layout.addWidget(self.country_label, 4, 0, 1, 1)
        self.postalcode_le = QtWidgets.QLineEdit(self.gridLayoutWidget_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.postalcode_le.sizePolicy().hasHeightForWidth())
        self.postalcode_le.setSizePolicy(sizePolicy)
        self.postalcode_le.setObjectName("postalcode_le")
        self.findpatient_adv_layout.addWidget(self.postalcode_le, 11, 0, 1, 1)
        self.gender_cb = QtWidgets.QComboBox(self.gridLayoutWidget_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gender_cb.sizePolicy().hasHeightForWidth())
        self.gender_cb.setSizePolicy(sizePolicy)
        self.gender_cb.setObjectName("gender_cb")
        self.gender_cb.addItem("")
        self.gender_cb.setItemText(0, "")
        self.gender_cb.addItem("")
        self.gender_cb.addItem("")
        self.findpatient_adv_layout.addWidget(self.gender_cb, 3, 0, 1, 1)
        self.dateofbirth_label = QtWidgets.QLabel(self.gridLayoutWidget_5)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.dateofbirth_label.setFont(font)
        self.dateofbirth_label.setAlignment(QtCore.Qt.AlignCenter)
        self.dateofbirth_label.setObjectName("dateofbirth_label")
        self.findpatient_adv_layout.addWidget(self.dateofbirth_label, 0, 0, 1, 1)
        self.dateofbirth_le = QtWidgets.QLineEdit(self.gridLayoutWidget_5)
        self.dateofbirth_le.setObjectName("dateofbirth_le")
        self.findpatient_adv_layout.addWidget(self.dateofbirth_le, 1, 0, 1, 1)
        self.findpatient_tab_widget.addTab(self.adv_param_tab, "")
        self.findpatient_layout.addWidget(self.findpatient_tab_widget, 3, 0, 1, 1)
        self.findpatient_showall_button = QtWidgets.QPushButton(self.credentials_tab)
        self.findpatient_showall_button.setObjectName("findpatient_showall_button")
        self.findpatient_layout.addWidget(self.findpatient_showall_button, 5, 0, 1, 1)
        self.enable_a_search = QtWidgets.QRadioButton(self.credentials_tab)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.enable_a_search.setFont(font)
        self.enable_a_search.setChecked(True)
        self.enable_a_search.setObjectName("enable_a_search")
        self.findpatient_layout.addWidget(self.enable_a_search, 2, 0, 1, 1)
        self.gridLayout_5.addLayout(self.findpatient_layout, 0, 0, 1, 1)
        self.patient_table = QtWidgets.QTableView(self.credentials_tab)
        self.patient_table.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.patient_table.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.patient_table.setSortingEnabled(True)
        self.patient_table.setObjectName("patient_table")
        self.gridLayout_5.addWidget(self.patient_table, 0, 1, 1, 1)
        self.tab_widget.addTab(self.credentials_tab, "")
        self.examination_tab = QtWidgets.QWidget()
        self.examination_tab.setObjectName("examination_tab")
        self.gridLayout = QtWidgets.QGridLayout(self.examination_tab)
        self.gridLayout.setObjectName("gridLayout")
        self.examination_table = QtWidgets.QTableView(self.examination_tab)
        self.examination_table.setFrameShadow(QtWidgets.QFrame.Plain)
        self.examination_table.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.examination_table.setSortingEnabled(True)
        self.examination_table.setObjectName("examination_table")
        self.gridLayout.addWidget(self.examination_table, 0, 1, 1, 1)
        self.examination_params_scrollarea = QtWidgets.QScrollArea(self.examination_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.examination_params_scrollarea.sizePolicy().hasHeightForWidth())
        self.examination_params_scrollarea.setSizePolicy(sizePolicy)
        self.examination_params_scrollarea.setMinimumSize(QtCore.QSize(300, 0))
        self.examination_params_scrollarea.setMaximumSize(QtCore.QSize(330, 16000))
        self.examination_params_scrollarea.setWidgetResizable(True)
        self.examination_params_scrollarea.setObjectName("examination_params_scrollarea")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 352, 639))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents_2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout_6 = QtWidgets.QGridLayout()
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.label_4 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label_4.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.gridLayout_6.addWidget(self.label_4, 5, 3, 1, 1)
        self.parameter_cb_1 = QtWidgets.QComboBox(self.scrollAreaWidgetContents_2)
        self.parameter_cb_1.setMaximumSize(QtCore.QSize(150, 16777215))
        self.parameter_cb_1.setObjectName("parameter_cb_1")
        self.parameter_cb_1.addItem("")
        self.parameter_cb_1.setItemText(0, "")
        self.parameter_cb_1.addItem("")
        self.parameter_cb_1.addItem("")
        self.parameter_cb_1.addItem("")
        self.parameter_cb_1.addItem("")
        self.parameter_cb_1.addItem("")
        self.parameter_cb_1.addItem("")
        self.parameter_cb_1.addItem("")
        self.parameter_cb_1.addItem("")
        self.parameter_cb_1.addItem("")
        self.parameter_cb_1.addItem("")
        self.gridLayout_6.addWidget(self.parameter_cb_1, 6, 1, 1, 1)
        self.parameter_le_1 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_2)
        self.parameter_le_1.setMaximumSize(QtCore.QSize(100, 16777215))
        self.parameter_le_1.setObjectName("parameter_le_1")
        self.gridLayout_6.addWidget(self.parameter_le_1, 6, 3, 1, 1)
        self.enable_label = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.enable_label.setMaximumSize(QtCore.QSize(30, 25))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.enable_label.setFont(font)
        self.enable_label.setAlignment(QtCore.Qt.AlignCenter)
        self.enable_label.setObjectName("enable_label")
        self.gridLayout_6.addWidget(self.enable_label, 5, 0, 1, 1)
        self.groupBox = QtWidgets.QGroupBox(self.scrollAreaWidgetContents_2)
        self.groupBox.setMaximumSize(QtCore.QSize(16777215, 300))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.groupBox.setFont(font)
        self.groupBox.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox.setObjectName("groupBox")
        self.formLayout_2 = QtWidgets.QFormLayout(self.groupBox)
        self.formLayout_2.setObjectName("formLayout_2")
        self.delete_criteria_button_1 = QtWidgets.QPushButton(self.groupBox)
        self.delete_criteria_button_1.setMaximumSize(QtCore.QSize(50, 16777215))
        self.delete_criteria_button_1.setObjectName("delete_criteria_button_1")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.delete_criteria_button_1)
        self.ex_label_1 = QtWidgets.QLabel(self.groupBox)
        self.ex_label_1.setMinimumSize(QtCore.QSize(200, 0))
        self.ex_label_1.setLineWidth(3)
        self.ex_label_1.setScaledContents(False)
        self.ex_label_1.setIndent(10)
        self.ex_label_1.setObjectName("ex_label_1")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.ex_label_1)
        self.ex_label_2 = QtWidgets.QLabel(self.groupBox)
        self.ex_label_2.setMinimumSize(QtCore.QSize(200, 0))
        self.ex_label_2.setLineWidth(3)
        self.ex_label_2.setScaledContents(False)
        self.ex_label_2.setIndent(10)
        self.ex_label_2.setObjectName("ex_label_2")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.ex_label_2)
        self.ex_label_3 = QtWidgets.QLabel(self.groupBox)
        self.ex_label_3.setMinimumSize(QtCore.QSize(200, 0))
        self.ex_label_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.ex_label_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.ex_label_3.setLineWidth(6)
        self.ex_label_3.setMidLineWidth(3)
        self.ex_label_3.setScaledContents(False)
        self.ex_label_3.setIndent(10)
        self.ex_label_3.setObjectName("ex_label_3")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.ex_label_3)
        self.ex_label_4 = QtWidgets.QLabel(self.groupBox)
        self.ex_label_4.setMinimumSize(QtCore.QSize(200, 0))
        self.ex_label_4.setLineWidth(3)
        self.ex_label_4.setScaledContents(False)
        self.ex_label_4.setIndent(10)
        self.ex_label_4.setObjectName("ex_label_4")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.ex_label_4)
        self.ex_label_5 = QtWidgets.QLabel(self.groupBox)
        self.ex_label_5.setMinimumSize(QtCore.QSize(200, 0))
        self.ex_label_5.setLineWidth(3)
        self.ex_label_5.setScaledContents(False)
        self.ex_label_5.setIndent(10)
        self.ex_label_5.setObjectName("ex_label_5")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.ex_label_5)
        self.ex_label_6 = QtWidgets.QLabel(self.groupBox)
        self.ex_label_6.setMinimumSize(QtCore.QSize(200, 0))
        self.ex_label_6.setLineWidth(3)
        self.ex_label_6.setScaledContents(False)
        self.ex_label_6.setIndent(10)
        self.ex_label_6.setObjectName("ex_label_6")
        self.formLayout_2.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.ex_label_6)
        self.ex_label_7 = QtWidgets.QLabel(self.groupBox)
        self.ex_label_7.setMinimumSize(QtCore.QSize(200, 0))
        self.ex_label_7.setLineWidth(3)
        self.ex_label_7.setScaledContents(False)
        self.ex_label_7.setIndent(10)
        self.ex_label_7.setObjectName("ex_label_7")
        self.formLayout_2.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.ex_label_7)
        self.ex_label_8 = QtWidgets.QLabel(self.groupBox)
        self.ex_label_8.setMinimumSize(QtCore.QSize(200, 0))
        self.ex_label_8.setLineWidth(3)
        self.ex_label_8.setScaledContents(False)
        self.ex_label_8.setIndent(10)
        self.ex_label_8.setObjectName("ex_label_8")
        self.formLayout_2.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.ex_label_8)
        self.label_13 = QtWidgets.QLabel(self.groupBox)
        self.label_13.setMinimumSize(QtCore.QSize(200, 0))
        self.label_13.setLineWidth(3)
        self.label_13.setScaledContents(False)
        self.label_13.setIndent(10)
        self.label_13.setObjectName("label_13")
        self.formLayout_2.setWidget(8, QtWidgets.QFormLayout.LabelRole, self.label_13)
        self.label_14 = QtWidgets.QLabel(self.groupBox)
        self.label_14.setMinimumSize(QtCore.QSize(200, 0))
        self.label_14.setLineWidth(3)
        self.label_14.setScaledContents(False)
        self.label_14.setIndent(10)
        self.label_14.setObjectName("label_14")
        self.formLayout_2.setWidget(9, QtWidgets.QFormLayout.LabelRole, self.label_14)
        self.label_15 = QtWidgets.QLabel(self.groupBox)
        self.label_15.setMinimumSize(QtCore.QSize(200, 0))
        self.label_15.setLineWidth(3)
        self.label_15.setScaledContents(False)
        self.label_15.setIndent(10)
        self.label_15.setObjectName("label_15")
        self.formLayout_2.setWidget(10, QtWidgets.QFormLayout.LabelRole, self.label_15)
        self.label_16 = QtWidgets.QLabel(self.groupBox)
        self.label_16.setMinimumSize(QtCore.QSize(200, 0))
        self.label_16.setLineWidth(3)
        self.label_16.setScaledContents(False)
        self.label_16.setIndent(10)
        self.label_16.setObjectName("label_16")
        self.formLayout_2.setWidget(11, QtWidgets.QFormLayout.LabelRole, self.label_16)
        self.label_17 = QtWidgets.QLabel(self.groupBox)
        self.label_17.setMinimumSize(QtCore.QSize(200, 0))
        self.label_17.setLineWidth(3)
        self.label_17.setScaledContents(False)
        self.label_17.setIndent(10)
        self.label_17.setObjectName("label_17")
        self.formLayout_2.setWidget(12, QtWidgets.QFormLayout.LabelRole, self.label_17)
        self.label_18 = QtWidgets.QLabel(self.groupBox)
        self.label_18.setMinimumSize(QtCore.QSize(200, 0))
        self.label_18.setLineWidth(3)
        self.label_18.setScaledContents(False)
        self.label_18.setIndent(10)
        self.label_18.setObjectName("label_18")
        self.formLayout_2.setWidget(13, QtWidgets.QFormLayout.LabelRole, self.label_18)
        self.delete_criteria_button_2 = QtWidgets.QPushButton(self.groupBox)
        self.delete_criteria_button_2.setMaximumSize(QtCore.QSize(50, 16777215))
        self.delete_criteria_button_2.setObjectName("delete_criteria_button_2")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.delete_criteria_button_2)
        self.delete_criteria_button_3 = QtWidgets.QPushButton(self.groupBox)
        self.delete_criteria_button_3.setMaximumSize(QtCore.QSize(50, 16777215))
        self.delete_criteria_button_3.setObjectName("delete_criteria_button_3")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.delete_criteria_button_3)
        self.delete_criteria_button_4 = QtWidgets.QPushButton(self.groupBox)
        self.delete_criteria_button_4.setMaximumSize(QtCore.QSize(50, 16777215))
        self.delete_criteria_button_4.setObjectName("delete_criteria_button_4")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.delete_criteria_button_4)
        self.delete_criteria_button_5 = QtWidgets.QPushButton(self.groupBox)
        self.delete_criteria_button_5.setMaximumSize(QtCore.QSize(50, 16777215))
        self.delete_criteria_button_5.setObjectName("delete_criteria_button_5")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.delete_criteria_button_5)
        self.delete_criteria_button_6 = QtWidgets.QPushButton(self.groupBox)
        self.delete_criteria_button_6.setMaximumSize(QtCore.QSize(50, 16777215))
        self.delete_criteria_button_6.setObjectName("delete_criteria_button_6")
        self.formLayout_2.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.delete_criteria_button_6)
        self.delete_criteria_button_7 = QtWidgets.QPushButton(self.groupBox)
        self.delete_criteria_button_7.setMaximumSize(QtCore.QSize(50, 16777215))
        self.delete_criteria_button_7.setObjectName("delete_criteria_button_7")
        self.formLayout_2.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.delete_criteria_button_7)
        self.pushButton_15 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_15.setMaximumSize(QtCore.QSize(50, 16777215))
        self.pushButton_15.setObjectName("pushButton_15")
        self.formLayout_2.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.pushButton_15)
        self.pushButton_16 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_16.setMaximumSize(QtCore.QSize(50, 16777215))
        self.pushButton_16.setObjectName("pushButton_16")
        self.formLayout_2.setWidget(8, QtWidgets.QFormLayout.FieldRole, self.pushButton_16)
        self.pushButton_17 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_17.setMaximumSize(QtCore.QSize(50, 16777215))
        self.pushButton_17.setObjectName("pushButton_17")
        self.formLayout_2.setWidget(9, QtWidgets.QFormLayout.FieldRole, self.pushButton_17)
        self.pushButton_18 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_18.setMaximumSize(QtCore.QSize(50, 16777215))
        self.pushButton_18.setObjectName("pushButton_18")
        self.formLayout_2.setWidget(10, QtWidgets.QFormLayout.FieldRole, self.pushButton_18)
        self.pushButton_19 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_19.setMaximumSize(QtCore.QSize(50, 16777215))
        self.pushButton_19.setObjectName("pushButton_19")
        self.formLayout_2.setWidget(11, QtWidgets.QFormLayout.FieldRole, self.pushButton_19)
        self.pushButton_20 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_20.setMaximumSize(QtCore.QSize(50, 16777215))
        self.pushButton_20.setObjectName("pushButton_20")
        self.formLayout_2.setWidget(12, QtWidgets.QFormLayout.FieldRole, self.pushButton_20)
        self.pushButton_21 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_21.setMaximumSize(QtCore.QSize(50, 16777215))
        self.pushButton_21.setObjectName("pushButton_21")
        self.formLayout_2.setWidget(13, QtWidgets.QFormLayout.FieldRole, self.pushButton_21)
        self.gridLayout_6.addWidget(self.groupBox, 2, 0, 1, 4)
        self.checkBox_4 = QtWidgets.QCheckBox(self.scrollAreaWidgetContents_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBox_4.sizePolicy().hasHeightForWidth())
        self.checkBox_4.setSizePolicy(sizePolicy)
        self.checkBox_4.setMaximumSize(QtCore.QSize(25, 16777215))
        self.checkBox_4.setText("")
        self.checkBox_4.setObjectName("checkBox_4")
        self.gridLayout_6.addWidget(self.checkBox_4, 8, 0, 1, 1)
        self.checkBox_5 = QtWidgets.QCheckBox(self.scrollAreaWidgetContents_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBox_5.sizePolicy().hasHeightForWidth())
        self.checkBox_5.setSizePolicy(sizePolicy)
        self.checkBox_5.setMaximumSize(QtCore.QSize(25, 16777215))
        self.checkBox_5.setText("")
        self.checkBox_5.setObjectName("checkBox_5")
        self.gridLayout_6.addWidget(self.checkBox_5, 10, 0, 1, 1)
        self.operator_cb_4 = QtWidgets.QComboBox(self.scrollAreaWidgetContents_2)
        self.operator_cb_4.setMinimumSize(QtCore.QSize(35, 0))
        self.operator_cb_4.setMaximumSize(QtCore.QSize(100, 16777215))
        self.operator_cb_4.setObjectName("operator_cb_4")
        self.operator_cb_4.addItem("")
        self.operator_cb_4.setItemText(0, "")
        self.operator_cb_4.addItem("")
        self.operator_cb_4.addItem("")
        self.operator_cb_4.addItem("")
        self.gridLayout_6.addWidget(self.operator_cb_4, 10, 2, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label_3.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout_6.addWidget(self.label_3, 5, 1, 1, 1)
        self.operator_cb_1 = QtWidgets.QComboBox(self.scrollAreaWidgetContents_2)
        self.operator_cb_1.setMinimumSize(QtCore.QSize(35, 0))
        self.operator_cb_1.setMaximumSize(QtCore.QSize(100, 16777215))
        self.operator_cb_1.setObjectName("operator_cb_1")
        self.operator_cb_1.addItem("")
        self.operator_cb_1.setItemText(0, "")
        self.operator_cb_1.addItem("")
        self.operator_cb_1.addItem("")
        self.operator_cb_1.addItem("")
        self.operator_cb_1.addItem("")
        self.gridLayout_6.addWidget(self.operator_cb_1, 6, 2, 1, 1)
        self.label_33 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label_33.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_33.setFont(font)
        self.label_33.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_33.setFrameShadow(QtWidgets.QFrame.Raised)
        self.label_33.setAlignment(QtCore.Qt.AlignCenter)
        self.label_33.setObjectName("label_33")
        self.gridLayout_6.addWidget(self.label_33, 0, 0, 1, 4)
        self.checkBox_2 = QtWidgets.QCheckBox(self.scrollAreaWidgetContents_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBox_2.sizePolicy().hasHeightForWidth())
        self.checkBox_2.setSizePolicy(sizePolicy)
        self.checkBox_2.setMaximumSize(QtCore.QSize(25, 16777215))
        self.checkBox_2.setText("")
        self.checkBox_2.setObjectName("checkBox_2")
        self.gridLayout_6.addWidget(self.checkBox_2, 6, 0, 1, 1)
        self.examination_search_reset_button = QtWidgets.QPushButton(self.scrollAreaWidgetContents_2)
        self.examination_search_reset_button.setObjectName("examination_search_reset_button")
        self.gridLayout_6.addWidget(self.examination_search_reset_button, 11, 2, 1, 2)
        self.operator_cb_2 = QtWidgets.QComboBox(self.scrollAreaWidgetContents_2)
        self.operator_cb_2.setMinimumSize(QtCore.QSize(35, 0))
        self.operator_cb_2.setMaximumSize(QtCore.QSize(100, 16777215))
        self.operator_cb_2.setObjectName("operator_cb_2")
        self.operator_cb_2.addItem("")
        self.operator_cb_2.setItemText(0, "")
        self.operator_cb_2.addItem("")
        self.operator_cb_2.addItem("")
        self.operator_cb_2.addItem("")
        self.gridLayout_6.addWidget(self.operator_cb_2, 7, 2, 1, 1)
        self.parameter_cb_4 = QtWidgets.QComboBox(self.scrollAreaWidgetContents_2)
        self.parameter_cb_4.setMaximumSize(QtCore.QSize(200, 16777215))
        self.parameter_cb_4.setObjectName("parameter_cb_4")
        self.parameter_cb_4.addItem("")
        self.parameter_cb_4.setItemText(0, "")
        self.parameter_cb_4.addItem("")
        self.parameter_cb_4.addItem("")
        self.parameter_cb_4.addItem("")
        self.parameter_cb_4.addItem("")
        self.parameter_cb_4.addItem("")
        self.parameter_cb_4.addItem("")
        self.parameter_cb_4.addItem("")
        self.parameter_cb_4.addItem("")
        self.parameter_cb_4.addItem("")
        self.parameter_cb_4.addItem("")
        self.gridLayout_6.addWidget(self.parameter_cb_4, 10, 1, 1, 1)
        self.operator_cb_3 = QtWidgets.QComboBox(self.scrollAreaWidgetContents_2)
        self.operator_cb_3.setMinimumSize(QtCore.QSize(35, 0))
        self.operator_cb_3.setMaximumSize(QtCore.QSize(100, 16777215))
        self.operator_cb_3.setObjectName("operator_cb_3")
        self.operator_cb_3.addItem("")
        self.operator_cb_3.setItemText(0, "")
        self.operator_cb_3.addItem("")
        self.operator_cb_3.addItem("")
        self.operator_cb_3.addItem("")
        self.gridLayout_6.addWidget(self.operator_cb_3, 8, 2, 1, 1)
        self.parameter_le_3 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_2)
        self.parameter_le_3.setMaximumSize(QtCore.QSize(100, 16777215))
        self.parameter_le_3.setObjectName("parameter_le_3")
        self.gridLayout_6.addWidget(self.parameter_le_3, 8, 3, 1, 1)
        self.examination_add_criteria_button = QtWidgets.QPushButton(self.scrollAreaWidgetContents_2)
        self.examination_add_criteria_button.setMaximumSize(QtCore.QSize(25, 16777215))
        self.examination_add_criteria_button.setObjectName("examination_add_criteria_button")
        self.gridLayout_6.addWidget(self.examination_add_criteria_button, 6, 4, 1, 1)
        self.parameter_cb_3 = QtWidgets.QComboBox(self.scrollAreaWidgetContents_2)
        self.parameter_cb_3.setMaximumSize(QtCore.QSize(200, 16777215))
        self.parameter_cb_3.setObjectName("parameter_cb_3")
        self.parameter_cb_3.addItem("")
        self.parameter_cb_3.setItemText(0, "")
        self.parameter_cb_3.addItem("")
        self.parameter_cb_3.addItem("")
        self.parameter_cb_3.addItem("")
        self.parameter_cb_3.addItem("")
        self.parameter_cb_3.addItem("")
        self.parameter_cb_3.addItem("")
        self.parameter_cb_3.addItem("")
        self.parameter_cb_3.addItem("")
        self.parameter_cb_3.addItem("")
        self.parameter_cb_3.addItem("")
        self.gridLayout_6.addWidget(self.parameter_cb_3, 8, 1, 1, 1)
        self.checkBox_3 = QtWidgets.QCheckBox(self.scrollAreaWidgetContents_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBox_3.sizePolicy().hasHeightForWidth())
        self.checkBox_3.setSizePolicy(sizePolicy)
        self.checkBox_3.setMaximumSize(QtCore.QSize(25, 16777215))
        self.checkBox_3.setText("")
        self.checkBox_3.setObjectName("checkBox_3")
        self.gridLayout_6.addWidget(self.checkBox_3, 7, 0, 1, 1)
        self.examination_search_button = QtWidgets.QPushButton(self.scrollAreaWidgetContents_2)
        self.examination_search_button.setObjectName("examination_search_button")
        self.gridLayout_6.addWidget(self.examination_search_button, 11, 1, 1, 1)
        self.parameter_le_4 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_2)
        self.parameter_le_4.setMaximumSize(QtCore.QSize(100, 16777215))
        self.parameter_le_4.setObjectName("parameter_le_4")
        self.gridLayout_6.addWidget(self.parameter_le_4, 10, 3, 1, 1)
        self.parameter_le_2 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_2)
        self.parameter_le_2.setMaximumSize(QtCore.QSize(100, 16777215))
        self.parameter_le_2.setObjectName("parameter_le_2")
        self.gridLayout_6.addWidget(self.parameter_le_2, 7, 1, 1, 1)
        self.parameter_le_5 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_2)
        self.parameter_le_5.setMaximumSize(QtCore.QSize(100, 16777215))
        self.parameter_le_5.setObjectName("parameter_le_5")
        self.gridLayout_6.addWidget(self.parameter_le_5, 7, 3, 1, 1)
        self.pushButton_22 = QtWidgets.QPushButton(self.scrollAreaWidgetContents_2)
        self.pushButton_22.setMaximumSize(QtCore.QSize(50, 16777215))
        self.pushButton_22.setObjectName("pushButton_22")
        self.gridLayout_6.addWidget(self.pushButton_22, 7, 4, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout_6, 1, 0, 1, 1)
        self.examination_params_scrollarea.setWidget(self.scrollAreaWidgetContents_2)
        self.gridLayout.addWidget(self.examination_params_scrollarea, 0, 0, 1, 1)
        self.tab_widget.addTab(self.examination_tab, "")
        self.irregularities_tab = QtWidgets.QWidget()
        self.irregularities_tab.setObjectName("irregularities_tab")
        self.tab_widget.addTab(self.irregularities_tab, "")
        self.statistics_tab = QtWidgets.QWidget()
        self.statistics_tab.setObjectName("statistics_tab")
        self.tab_widget.addTab(self.statistics_tab, "")
        self.gridLayout_4.addWidget(self.tab_widget, 0, 0, 1, 1)
        main_app_window.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(main_app_window)
        self.statusbar.setObjectName("statusbar")
        main_app_window.setStatusBar(self.statusbar)

        self.retranslateUi(main_app_window)
        self.tab_widget.setCurrentIndex(2)
        self.findpatient_tab_widget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(main_app_window)
        main_app_window.setTabOrder(self.name_le, self.surname_le)
        main_app_window.setTabOrder(self.surname_le, self.pesel_le)
        main_app_window.setTabOrder(self.pesel_le, self.dateofbirth_le)
        main_app_window.setTabOrder(self.dateofbirth_le, self.gender_cb)
        main_app_window.setTabOrder(self.gender_cb, self.country_cb)
        main_app_window.setTabOrder(self.country_cb, self.phonenumber_le)
        main_app_window.setTabOrder(self.phonenumber_le, self.city_le)
        main_app_window.setTabOrder(self.city_le, self.postalcode_le)
        main_app_window.setTabOrder(self.postalcode_le, self.findpatient_search_button)
        main_app_window.setTabOrder(self.findpatient_search_button, self.findpatient_showall_button)
        main_app_window.setTabOrder(self.findpatient_showall_button, self.findpatient_tab_widget)
        main_app_window.setTabOrder(self.findpatient_tab_widget, self.checkBox_2)
        main_app_window.setTabOrder(self.checkBox_2, self.operator_cb_1)
        main_app_window.setTabOrder(self.operator_cb_1, self.parameter_le_1)
        main_app_window.setTabOrder(self.parameter_le_1, self.examination_table)
        main_app_window.setTabOrder(self.examination_table, self.patient_table)

    def retranslateUi(self, main_app_window):
        _translate = QtCore.QCoreApplication.translate
        main_app_window.setWindowTitle(_translate("main_app_window", "MainWindow"))
        self.label.setText(_translate("main_app_window", "Remote Health Monitoring System Application"))
        self.tab_widget.setTabText(self.tab_widget.indexOf(self.general_tab), _translate("main_app_window", "General"))
        self.findpatient_search_button.setText(_translate("main_app_window", "Search"))
        self.findpatient_label.setText(_translate("main_app_window", "Find a patient"))
        self.name_label.setText(_translate("main_app_window", "Name"))
        self.pesel_label.setText(_translate("main_app_window", "PESEL"))
        self.surname_label.setText(_translate("main_app_window", "Surname"))
        self.findpatient_tab_widget.setTabText(self.findpatient_tab_widget.indexOf(self.basic_param_tab), _translate("main_app_window", "Basic Search"))
        self.gender_label.setText(_translate("main_app_window", "Gender"))
        self.city_label.setText(_translate("main_app_window", "City"))
        self.phonenumber_label.setText(_translate("main_app_window", "Phone number"))
        self.postalcode_label.setText(_translate("main_app_window", "Postal code"))
        self.country_cb.setItemText(1, _translate("main_app_window", "Austria"))
        self.country_cb.setItemText(2, _translate("main_app_window", "Czech Republic"))
        self.country_cb.setItemText(3, _translate("main_app_window", "France"))
        self.country_cb.setItemText(4, _translate("main_app_window", "Germany"))
        self.country_cb.setItemText(5, _translate("main_app_window", "Italy"))
        self.country_cb.setItemText(6, _translate("main_app_window", "Poland"))
        self.country_cb.setItemText(7, _translate("main_app_window", "Portugal"))
        self.country_cb.setItemText(8, _translate("main_app_window", "Russia"))
        self.country_cb.setItemText(9, _translate("main_app_window", "Spain"))
        self.country_cb.setItemText(10, _translate("main_app_window", "Uk"))
        self.country_cb.setItemText(11, _translate("main_app_window", "USA"))
        self.country_label.setText(_translate("main_app_window", "Country"))
        self.gender_cb.setItemText(1, _translate("main_app_window", "M"))
        self.gender_cb.setItemText(2, _translate("main_app_window", "F"))
        self.dateofbirth_label.setText(_translate("main_app_window", "Date of birth"))
        self.findpatient_tab_widget.setTabText(self.findpatient_tab_widget.indexOf(self.adv_param_tab), _translate("main_app_window", "Advanced Search"))
        self.findpatient_showall_button.setText(_translate("main_app_window", "Show All"))
        self.enable_a_search.setText(_translate("main_app_window", "Show Many"))
        self.tab_widget.setTabText(self.tab_widget.indexOf(self.credentials_tab), _translate("main_app_window", "Patient Credentials"))
        self.label_4.setText(_translate("main_app_window", "Value"))
        self.parameter_cb_1.setItemText(1, _translate("main_app_window", "Name"))
        self.parameter_cb_1.setItemText(2, _translate("main_app_window", "Surname"))
        self.parameter_cb_1.setItemText(3, _translate("main_app_window", "Examination Date"))
        self.parameter_cb_1.setItemText(4, _translate("main_app_window", "Systolic Pressure"))
        self.parameter_cb_1.setItemText(5, _translate("main_app_window", "Diastolic Pressure"))
        self.parameter_cb_1.setItemText(6, _translate("main_app_window", "Heart Rate"))
        self.parameter_cb_1.setItemText(7, _translate("main_app_window", "Patient Height"))
        self.parameter_cb_1.setItemText(8, _translate("main_app_window", "Patient Weight"))
        self.parameter_cb_1.setItemText(9, _translate("main_app_window", "BMI"))
        self.parameter_cb_1.setItemText(10, _translate("main_app_window", "Parameter Warning"))
        self.enable_label.setText(_translate("main_app_window", " Enable"))
        self.groupBox.setTitle(_translate("main_app_window", "Applied Criteria"))
        self.delete_criteria_button_1.setText(_translate("main_app_window", "-"))
        self.ex_label_1.setText(_translate("main_app_window", "TextLabel"))
        self.ex_label_2.setText(_translate("main_app_window", "TextLabel"))
        self.ex_label_3.setText(_translate("main_app_window", "TextLabel"))
        self.ex_label_4.setText(_translate("main_app_window", "TextLabel"))
        self.ex_label_5.setText(_translate("main_app_window", "TextLabel"))
        self.ex_label_6.setText(_translate("main_app_window", "TextLabel"))
        self.ex_label_7.setText(_translate("main_app_window", "TextLabel"))
        self.ex_label_8.setText(_translate("main_app_window", "TextLabel"))
        self.label_13.setText(_translate("main_app_window", "TextLabel"))
        self.label_14.setText(_translate("main_app_window", "TextLabel"))
        self.label_15.setText(_translate("main_app_window", "TextLabel"))
        self.label_16.setText(_translate("main_app_window", "TextLabel"))
        self.label_17.setText(_translate("main_app_window", "TextLabel"))
        self.label_18.setText(_translate("main_app_window", "TextLabel"))
        self.delete_criteria_button_2.setText(_translate("main_app_window", "-"))
        self.delete_criteria_button_3.setText(_translate("main_app_window", "-"))
        self.delete_criteria_button_4.setText(_translate("main_app_window", "-"))
        self.delete_criteria_button_5.setText(_translate("main_app_window", "-"))
        self.delete_criteria_button_6.setText(_translate("main_app_window", "-"))
        self.delete_criteria_button_7.setText(_translate("main_app_window", "-"))
        self.pushButton_15.setText(_translate("main_app_window", "-"))
        self.pushButton_16.setText(_translate("main_app_window", "-"))
        self.pushButton_17.setText(_translate("main_app_window", "-"))
        self.pushButton_18.setText(_translate("main_app_window", "-"))
        self.pushButton_19.setText(_translate("main_app_window", "-"))
        self.pushButton_20.setText(_translate("main_app_window", "-"))
        self.pushButton_21.setText(_translate("main_app_window", "-"))
        self.operator_cb_4.setItemText(1, _translate("main_app_window", ">"))
        self.operator_cb_4.setItemText(2, _translate("main_app_window", "<"))
        self.operator_cb_4.setItemText(3, _translate("main_app_window", "="))
        self.label_3.setText(_translate("main_app_window", "Parameter Name"))
        self.operator_cb_1.setItemText(1, _translate("main_app_window", ">"))
        self.operator_cb_1.setItemText(2, _translate("main_app_window", "<"))
        self.operator_cb_1.setItemText(3, _translate("main_app_window", "="))
        self.operator_cb_1.setItemText(4, _translate("main_app_window", "Text Like"))
        self.label_33.setText(_translate("main_app_window", "Apply Examination Criteria"))
        self.examination_search_reset_button.setText(_translate("main_app_window", "Show All"))
        self.operator_cb_2.setItemText(1, _translate("main_app_window", ">"))
        self.operator_cb_2.setItemText(2, _translate("main_app_window", "<"))
        self.operator_cb_2.setItemText(3, _translate("main_app_window", "="))
        self.parameter_cb_4.setItemText(1, _translate("main_app_window", "Name"))
        self.parameter_cb_4.setItemText(2, _translate("main_app_window", "Surname"))
        self.parameter_cb_4.setItemText(3, _translate("main_app_window", "Examination Date"))
        self.parameter_cb_4.setItemText(4, _translate("main_app_window", "Systolic Pressure"))
        self.parameter_cb_4.setItemText(5, _translate("main_app_window", "Diastolic Pressure"))
        self.parameter_cb_4.setItemText(6, _translate("main_app_window", "Heart Rate"))
        self.parameter_cb_4.setItemText(7, _translate("main_app_window", "Patient Height"))
        self.parameter_cb_4.setItemText(8, _translate("main_app_window", "Patient Weight"))
        self.parameter_cb_4.setItemText(9, _translate("main_app_window", "BMI"))
        self.parameter_cb_4.setItemText(10, _translate("main_app_window", "Parameter Warning"))
        self.operator_cb_3.setItemText(1, _translate("main_app_window", ">"))
        self.operator_cb_3.setItemText(2, _translate("main_app_window", "<"))
        self.operator_cb_3.setItemText(3, _translate("main_app_window", "="))
        self.examination_add_criteria_button.setText(_translate("main_app_window", "+"))
        self.parameter_cb_3.setItemText(1, _translate("main_app_window", "Name"))
        self.parameter_cb_3.setItemText(2, _translate("main_app_window", "Surname"))
        self.parameter_cb_3.setItemText(3, _translate("main_app_window", "Examination Date"))
        self.parameter_cb_3.setItemText(4, _translate("main_app_window", "Systolic Pressure"))
        self.parameter_cb_3.setItemText(5, _translate("main_app_window", "Diastolic Pressure"))
        self.parameter_cb_3.setItemText(6, _translate("main_app_window", "Heart Rate"))
        self.parameter_cb_3.setItemText(7, _translate("main_app_window", "Patient Height"))
        self.parameter_cb_3.setItemText(8, _translate("main_app_window", "Patient Weight"))
        self.parameter_cb_3.setItemText(9, _translate("main_app_window", "BMI"))
        self.parameter_cb_3.setItemText(10, _translate("main_app_window", "Parameter Warning"))
        self.examination_search_button.setText(_translate("main_app_window", "Search"))
        self.parameter_le_2.setText(_translate("main_app_window", "REMOVE CRITERIA"))
        self.parameter_le_5.setText(_translate("main_app_window", "index number"))
        self.pushButton_22.setText(_translate("main_app_window", "-"))
        self.tab_widget.setTabText(self.tab_widget.indexOf(self.examination_tab), _translate("main_app_window", "Patient Examination"))
        self.tab_widget.setTabText(self.tab_widget.indexOf(self.irregularities_tab), _translate("main_app_window", "Irregularities"))
        self.tab_widget.setTabText(self.tab_widget.indexOf(self.statistics_tab), _translate("main_app_window", "Statistics"))

