# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ApplicationWindow.ui'
#
# Created by: PyQt5 UI code generator 5.4.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_main_app_window(object):
    def setupUi(self, main_app_window):
        main_app_window.setObjectName("main_app_window")
        main_app_window.setWindowModality(QtCore.Qt.NonModal)
        main_app_window.resize(1206, 740)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(main_app_window.sizePolicy().hasHeightForWidth())
        main_app_window.setSizePolicy(sizePolicy)
        self.centralwidget = QtWidgets.QWidget(main_app_window)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.tab_widget = QtWidgets.QTabWidget(self.centralwidget)
        self.tab_widget.setStyleSheet("")
        self.tab_widget.setObjectName("tab_widget")
        self.general_tab = QtWidgets.QWidget()
        self.general_tab.setObjectName("general_tab")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.general_tab)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label = QtWidgets.QLabel(self.general_tab)
        self.label.setMaximumSize(QtCore.QSize(16777215, 100))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setTextFormat(QtCore.Qt.RichText)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setWordWrap(False)
        self.label.setObjectName("label")
        self.gridLayout_3.addWidget(self.label, 0, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.general_tab)
        self.label_2.setObjectName("label_2")
        self.gridLayout_3.addWidget(self.label_2, 1, 0, 1, 1)
        self.gridLayout_7.addLayout(self.gridLayout_3, 0, 0, 1, 1)
        self.tab_widget.addTab(self.general_tab, "")
        self.credentials_tab = QtWidgets.QWidget()
        self.credentials_tab.setObjectName("credentials_tab")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.credentials_tab)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.findpatient_layout = QtWidgets.QGridLayout()
        self.findpatient_layout.setObjectName("findpatient_layout")
        self.findpatient_tab_widget = QtWidgets.QTabWidget(self.credentials_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.findpatient_tab_widget.sizePolicy().hasHeightForWidth())
        self.findpatient_tab_widget.setSizePolicy(sizePolicy)
        self.findpatient_tab_widget.setMaximumSize(QtCore.QSize(200, 16777215))
        self.findpatient_tab_widget.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.findpatient_tab_widget.setElideMode(QtCore.Qt.ElideLeft)
        self.findpatient_tab_widget.setObjectName("findpatient_tab_widget")
        self.basic_param_tab = QtWidgets.QWidget()
        self.basic_param_tab.setObjectName("basic_param_tab")
        self.gridLayoutWidget_6 = QtWidgets.QWidget(self.basic_param_tab)
        self.gridLayoutWidget_6.setGeometry(QtCore.QRect(0, 0, 191, 171))
        self.gridLayoutWidget_6.setObjectName("gridLayoutWidget_6")
        self.findpatient_basic_layout = QtWidgets.QGridLayout(self.gridLayoutWidget_6)
        self.findpatient_basic_layout.setContentsMargins(0, 0, 0, 0)
        self.findpatient_basic_layout.setObjectName("findpatient_basic_layout")
        self.pesel_le = QtWidgets.QLineEdit(self.gridLayoutWidget_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pesel_le.sizePolicy().hasHeightForWidth())
        self.pesel_le.setSizePolicy(sizePolicy)
        self.pesel_le.setObjectName("pesel_le")
        self.findpatient_basic_layout.addWidget(self.pesel_le, 7, 0, 1, 1)
        self.surname_le = QtWidgets.QLineEdit(self.gridLayoutWidget_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.surname_le.sizePolicy().hasHeightForWidth())
        self.surname_le.setSizePolicy(sizePolicy)
        self.surname_le.setObjectName("surname_le")
        self.findpatient_basic_layout.addWidget(self.surname_le, 4, 0, 1, 1)
        self.name_label = QtWidgets.QLabel(self.gridLayoutWidget_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.name_label.sizePolicy().hasHeightForWidth())
        self.name_label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.name_label.setFont(font)
        self.name_label.setAlignment(QtCore.Qt.AlignCenter)
        self.name_label.setObjectName("name_label")
        self.findpatient_basic_layout.addWidget(self.name_label, 0, 0, 1, 1)
        self.name_le = QtWidgets.QLineEdit(self.gridLayoutWidget_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.name_le.sizePolicy().hasHeightForWidth())
        self.name_le.setSizePolicy(sizePolicy)
        self.name_le.setObjectName("name_le")
        self.findpatient_basic_layout.addWidget(self.name_le, 1, 0, 1, 1)
        self.pesel_label = QtWidgets.QLabel(self.gridLayoutWidget_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pesel_label.sizePolicy().hasHeightForWidth())
        self.pesel_label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pesel_label.setFont(font)
        self.pesel_label.setAlignment(QtCore.Qt.AlignCenter)
        self.pesel_label.setObjectName("pesel_label")
        self.findpatient_basic_layout.addWidget(self.pesel_label, 5, 0, 1, 1)
        self.surname_label = QtWidgets.QLabel(self.gridLayoutWidget_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.surname_label.sizePolicy().hasHeightForWidth())
        self.surname_label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.surname_label.setFont(font)
        self.surname_label.setAutoFillBackground(False)
        self.surname_label.setTextFormat(QtCore.Qt.AutoText)
        self.surname_label.setScaledContents(False)
        self.surname_label.setAlignment(QtCore.Qt.AlignCenter)
        self.surname_label.setObjectName("surname_label")
        self.findpatient_basic_layout.addWidget(self.surname_label, 2, 0, 1, 1)
        self.findpatient_tab_widget.addTab(self.basic_param_tab, "")
        self.adv_param_tab = QtWidgets.QWidget()
        self.adv_param_tab.setObjectName("adv_param_tab")
        self.gridLayoutWidget_5 = QtWidgets.QWidget(self.adv_param_tab)
        self.gridLayoutWidget_5.setGeometry(QtCore.QRect(0, 0, 252, 314))
        self.gridLayoutWidget_5.setObjectName("gridLayoutWidget_5")
        self.findpatient_adv_layout = QtWidgets.QGridLayout(self.gridLayoutWidget_5)
        self.findpatient_adv_layout.setContentsMargins(0, 0, 0, 0)
        self.findpatient_adv_layout.setObjectName("findpatient_adv_layout")
        self.gender_label = QtWidgets.QLabel(self.gridLayoutWidget_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gender_label.sizePolicy().hasHeightForWidth())
        self.gender_label.setSizePolicy(sizePolicy)
        self.gender_label.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.gender_label.setFont(font)
        self.gender_label.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.gender_label.setObjectName("gender_label")
        self.findpatient_adv_layout.addWidget(self.gender_label, 2, 0, 1, 1)
        self.city_label = QtWidgets.QLabel(self.gridLayoutWidget_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.city_label.sizePolicy().hasHeightForWidth())
        self.city_label.setSizePolicy(sizePolicy)
        self.city_label.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.city_label.setFont(font)
        self.city_label.setAlignment(QtCore.Qt.AlignCenter)
        self.city_label.setObjectName("city_label")
        self.findpatient_adv_layout.addWidget(self.city_label, 8, 0, 1, 1)
        self.phonenumber_label = QtWidgets.QLabel(self.gridLayoutWidget_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.phonenumber_label.sizePolicy().hasHeightForWidth())
        self.phonenumber_label.setSizePolicy(sizePolicy)
        self.phonenumber_label.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.phonenumber_label.setFont(font)
        self.phonenumber_label.setAlignment(QtCore.Qt.AlignCenter)
        self.phonenumber_label.setObjectName("phonenumber_label")
        self.findpatient_adv_layout.addWidget(self.phonenumber_label, 6, 0, 1, 1)
        self.phonenumber_le = QtWidgets.QLineEdit(self.gridLayoutWidget_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.phonenumber_le.sizePolicy().hasHeightForWidth())
        self.phonenumber_le.setSizePolicy(sizePolicy)
        self.phonenumber_le.setMaximumSize(QtCore.QSize(195, 16777215))
        self.phonenumber_le.setObjectName("phonenumber_le")
        self.findpatient_adv_layout.addWidget(self.phonenumber_le, 7, 0, 1, 1)
        self.postalcode_label = QtWidgets.QLabel(self.gridLayoutWidget_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.postalcode_label.sizePolicy().hasHeightForWidth())
        self.postalcode_label.setSizePolicy(sizePolicy)
        self.postalcode_label.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.postalcode_label.setFont(font)
        self.postalcode_label.setAlignment(QtCore.Qt.AlignCenter)
        self.postalcode_label.setObjectName("postalcode_label")
        self.findpatient_adv_layout.addWidget(self.postalcode_label, 10, 0, 1, 1)
        self.city_le = QtWidgets.QLineEdit(self.gridLayoutWidget_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.city_le.sizePolicy().hasHeightForWidth())
        self.city_le.setSizePolicy(sizePolicy)
        self.city_le.setMaximumSize(QtCore.QSize(195, 16777215))
        self.city_le.setObjectName("city_le")
        self.findpatient_adv_layout.addWidget(self.city_le, 9, 0, 1, 1)
        self.country_cb = QtWidgets.QComboBox(self.gridLayoutWidget_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.country_cb.sizePolicy().hasHeightForWidth())
        self.country_cb.setSizePolicy(sizePolicy)
        self.country_cb.setMaximumSize(QtCore.QSize(195, 16777215))
        self.country_cb.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContents)
        self.country_cb.setObjectName("country_cb")
        self.country_cb.addItem("")
        self.country_cb.setItemText(0, "")
        self.country_cb.addItem("")
        self.country_cb.addItem("")
        self.country_cb.addItem("")
        self.country_cb.addItem("")
        self.country_cb.addItem("")
        self.country_cb.addItem("")
        self.country_cb.addItem("")
        self.country_cb.addItem("")
        self.country_cb.addItem("")
        self.country_cb.addItem("")
        self.country_cb.addItem("")
        self.country_cb.addItem("")
        self.country_cb.addItem("")
        self.country_cb.addItem("")
        self.country_cb.addItem("")
        self.country_cb.addItem("")
        self.country_cb.addItem("")
        self.country_cb.addItem("")
        self.country_cb.addItem("")
        self.country_cb.addItem("")
        self.country_cb.addItem("")
        self.country_cb.addItem("")
        self.country_cb.addItem("")
        self.country_cb.addItem("")
        self.country_cb.addItem("")
        self.country_cb.addItem("")
        self.country_cb.addItem("")
        self.country_cb.addItem("")
        self.country_cb.addItem("")
        self.country_cb.addItem("")
        self.country_cb.addItem("")
        self.country_cb.addItem("")
        self.country_cb.addItem("")
        self.country_cb.addItem("")
        self.country_cb.addItem("")
        self.country_cb.addItem("")
        self.country_cb.addItem("")
        self.country_cb.addItem("")
        self.country_cb.addItem("")
        self.country_cb.addItem("")
        self.country_cb.addItem("")
        self.country_cb.addItem("")
        self.country_cb.addItem("")
        self.country_cb.addItem("")
        self.country_cb.addItem("")
        self.country_cb.addItem("")
        self.country_cb.addItem("")
        self.country_cb.addItem("")
        self.country_cb.addItem("")
        self.country_cb.addItem("")
        self.country_cb.addItem("")
        self.country_cb.addItem("")
        self.country_cb.addItem("")
        self.country_cb.addItem("")
        self.country_cb.addItem("")
        self.country_cb.addItem("")
        self.country_cb.addItem("")
        self.country_cb.addItem("")
        self.country_cb.addItem("")
        self.country_cb.addItem("")
        self.country_cb.addItem("")
        self.country_cb.addItem("")
        self.country_cb.addItem("")
        self.country_cb.addItem("")
        self.country_cb.addItem("")
        self.country_cb.addItem("")
        self.country_cb.addItem("")
        self.country_cb.addItem("")
        self.country_cb.addItem("")
        self.country_cb.addItem("")
        self.country_cb.addItem("")
        self.country_cb.addItem("")
        self.country_cb.addItem("")
        self.country_cb.addItem("")
        self.country_cb.addItem("")
        self.country_cb.addItem("")
        self.country_cb.addItem("")
        self.country_cb.addItem("")
        self.country_cb.addItem("")
        self.country_cb.addItem("")
        self.country_cb.addItem("")
        self.country_cb.addItem("")
        self.country_cb.addItem("")
        self.country_cb.addItem("")
        self.country_cb.addItem("")
        self.country_cb.addItem("")
        self.country_cb.addItem("")
        self.country_cb.addItem("")
        self.country_cb.addItem("")
        self.country_cb.addItem("")
        self.country_cb.addItem("")
        self.country_cb.addItem("")
        self.country_cb.addItem("")
        self.country_cb.addItem("")
        self.country_cb.addItem("")
        self.country_cb.addItem("")
        self.country_cb.addItem("")
        self.country_cb.addItem("")
        self.country_cb.addItem("")
        self.country_cb.addItem("")
        self.country_cb.addItem("")
        self.country_cb.addItem("")
        self.country_cb.addItem("")
        self.country_cb.addItem("")
        self.country_cb.addItem("")
        self.country_cb.addItem("")
        self.country_cb.addItem("")
        self.country_cb.addItem("")
        self.country_cb.addItem("")
        self.country_cb.addItem("")
        self.country_cb.addItem("")
        self.country_cb.addItem("")
        self.country_cb.addItem("")
        self.country_cb.addItem("")
        self.country_cb.addItem("")
        self.country_cb.addItem("")
        self.country_cb.addItem("")
        self.country_cb.addItem("")
        self.country_cb.addItem("")
        self.country_cb.addItem("")
        self.country_cb.addItem("")
        self.country_cb.addItem("")
        self.country_cb.addItem("")
        self.country_cb.addItem("")
        self.country_cb.addItem("")
        self.country_cb.addItem("")
        self.country_cb.addItem("")
        self.country_cb.addItem("")
        self.country_cb.addItem("")
        self.country_cb.addItem("")
        self.country_cb.addItem("")
        self.country_cb.addItem("")
        self.country_cb.addItem("")
        self.country_cb.addItem("")
        self.country_cb.addItem("")
        self.country_cb.addItem("")
        self.country_cb.addItem("")
        self.country_cb.addItem("")
        self.country_cb.addItem("")
        self.country_cb.addItem("")
        self.country_cb.addItem("")
        self.country_cb.addItem("")
        self.country_cb.addItem("")
        self.country_cb.addItem("")
        self.country_cb.addItem("")
        self.country_cb.addItem("")
        self.country_cb.addItem("")
        self.country_cb.addItem("")
        self.country_cb.addItem("")
        self.country_cb.addItem("")
        self.country_cb.addItem("")
        self.country_cb.addItem("")
        self.country_cb.addItem("")
        self.country_cb.addItem("")
        self.country_cb.addItem("")
        self.country_cb.addItem("")
        self.country_cb.addItem("")
        self.country_cb.addItem("")
        self.country_cb.addItem("")
        self.country_cb.addItem("")
        self.country_cb.addItem("")
        self.country_cb.addItem("")
        self.country_cb.addItem("")
        self.country_cb.addItem("")
        self.country_cb.addItem("")
        self.country_cb.addItem("")
        self.country_cb.addItem("")
        self.country_cb.addItem("")
        self.country_cb.addItem("")
        self.country_cb.addItem("")
        self.country_cb.addItem("")
        self.country_cb.addItem("")
        self.country_cb.addItem("")
        self.country_cb.addItem("")
        self.country_cb.addItem("")
        self.country_cb.addItem("")
        self.country_cb.addItem("")
        self.country_cb.addItem("")
        self.country_cb.addItem("")
        self.country_cb.addItem("")
        self.country_cb.addItem("")
        self.country_cb.addItem("")
        self.country_cb.addItem("")
        self.country_cb.addItem("")
        self.country_cb.addItem("")
        self.country_cb.addItem("")
        self.country_cb.addItem("")
        self.country_cb.addItem("")
        self.country_cb.addItem("")
        self.country_cb.addItem("")
        self.country_cb.addItem("")
        self.country_cb.addItem("")
        self.country_cb.addItem("")
        self.country_cb.addItem("")
        self.country_cb.addItem("")
        self.country_cb.addItem("")
        self.country_cb.addItem("")
        self.country_cb.addItem("")
        self.country_cb.addItem("")
        self.country_cb.addItem("")
        self.country_cb.addItem("")
        self.country_cb.addItem("")
        self.country_cb.addItem("")
        self.country_cb.addItem("")
        self.country_cb.addItem("")
        self.country_cb.addItem("")
        self.country_cb.addItem("")
        self.country_cb.addItem("")
        self.country_cb.addItem("")
        self.country_cb.addItem("")
        self.country_cb.addItem("")
        self.country_cb.addItem("")
        self.country_cb.addItem("")
        self.country_cb.addItem("")
        self.country_cb.addItem("")
        self.country_cb.addItem("")
        self.country_cb.addItem("")
        self.country_cb.addItem("")
        self.country_cb.addItem("")
        self.country_cb.addItem("")
        self.country_cb.addItem("")
        self.country_cb.addItem("")
        self.country_cb.addItem("")
        self.country_cb.addItem("")
        self.country_cb.addItem("")
        self.country_cb.addItem("")
        self.country_cb.addItem("")
        self.country_cb.addItem("")
        self.country_cb.addItem("")
        self.country_cb.addItem("")
        self.country_cb.addItem("")
        self.country_cb.addItem("")
        self.country_cb.addItem("")
        self.country_cb.addItem("")
        self.country_cb.addItem("")
        self.country_cb.addItem("")
        self.country_cb.addItem("")
        self.country_cb.addItem("")
        self.country_cb.addItem("")
        self.country_cb.addItem("")
        self.country_cb.addItem("")
        self.findpatient_adv_layout.addWidget(self.country_cb, 5, 0, 1, 1)
        self.country_label = QtWidgets.QLabel(self.gridLayoutWidget_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.country_label.sizePolicy().hasHeightForWidth())
        self.country_label.setSizePolicy(sizePolicy)
        self.country_label.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.country_label.setFont(font)
        self.country_label.setAlignment(QtCore.Qt.AlignCenter)
        self.country_label.setObjectName("country_label")
        self.findpatient_adv_layout.addWidget(self.country_label, 4, 0, 1, 1)
        self.postalcode_le = QtWidgets.QLineEdit(self.gridLayoutWidget_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.postalcode_le.sizePolicy().hasHeightForWidth())
        self.postalcode_le.setSizePolicy(sizePolicy)
        self.postalcode_le.setMaximumSize(QtCore.QSize(195, 16777215))
        self.postalcode_le.setObjectName("postalcode_le")
        self.findpatient_adv_layout.addWidget(self.postalcode_le, 11, 0, 1, 1)
        self.gender_cb = QtWidgets.QComboBox(self.gridLayoutWidget_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gender_cb.sizePolicy().hasHeightForWidth())
        self.gender_cb.setSizePolicy(sizePolicy)
        self.gender_cb.setMaximumSize(QtCore.QSize(195, 16777215))
        self.gender_cb.setObjectName("gender_cb")
        self.gender_cb.addItem("")
        self.gender_cb.setItemText(0, "")
        self.gender_cb.addItem("")
        self.gender_cb.addItem("")
        self.findpatient_adv_layout.addWidget(self.gender_cb, 3, 0, 1, 1)
        self.dateofbirth_label = QtWidgets.QLabel(self.gridLayoutWidget_5)
        self.dateofbirth_label.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.dateofbirth_label.setFont(font)
        self.dateofbirth_label.setAlignment(QtCore.Qt.AlignCenter)
        self.dateofbirth_label.setObjectName("dateofbirth_label")
        self.findpatient_adv_layout.addWidget(self.dateofbirth_label, 0, 0, 1, 1)
        self.dateofbirth_le = QtWidgets.QLineEdit(self.gridLayoutWidget_5)
        self.dateofbirth_le.setObjectName("dateofbirth_le")
        self.findpatient_adv_layout.addWidget(self.dateofbirth_le, 1, 0, 1, 1)
        self.findpatient_tab_widget.addTab(self.adv_param_tab, "")
        self.findpatient_layout.addWidget(self.findpatient_tab_widget, 3, 0, 1, 1)
        self.findpatient_showall_button = QtWidgets.QPushButton(self.credentials_tab)
        self.findpatient_showall_button.setObjectName("findpatient_showall_button")
        self.findpatient_layout.addWidget(self.findpatient_showall_button, 5, 0, 1, 1)
        self.enable_a_search = QtWidgets.QRadioButton(self.credentials_tab)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.enable_a_search.setFont(font)
        self.enable_a_search.setChecked(True)
        self.enable_a_search.setObjectName("enable_a_search")
        self.findpatient_layout.addWidget(self.enable_a_search, 2, 0, 1, 1)
        self.findpatient_search_button = QtWidgets.QPushButton(self.credentials_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.findpatient_search_button.sizePolicy().hasHeightForWidth())
        self.findpatient_search_button.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.findpatient_search_button.setFont(font)
        self.findpatient_search_button.setObjectName("findpatient_search_button")
        self.findpatient_layout.addWidget(self.findpatient_search_button, 4, 0, 1, 1)
        self.findpatient_label = QtWidgets.QLabel(self.credentials_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.findpatient_label.sizePolicy().hasHeightForWidth())
        self.findpatient_label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        self.findpatient_label.setFont(font)
        self.findpatient_label.setAutoFillBackground(False)
        self.findpatient_label.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.findpatient_label.setFrameShadow(QtWidgets.QFrame.Raised)
        self.findpatient_label.setLineWidth(4)
        self.findpatient_label.setMidLineWidth(2)
        self.findpatient_label.setAlignment(QtCore.Qt.AlignCenter)
        self.findpatient_label.setWordWrap(False)
        self.findpatient_label.setContentsMargins(1, 1, 1, 1)
        self.findpatient_label.setIndent(-1)
        self.findpatient_label.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.findpatient_label.setObjectName("findpatient_label")
        self.findpatient_layout.addWidget(self.findpatient_label, 1, 0, 1, 1)
        self.findpatient_export_button = QtWidgets.QPushButton(self.credentials_tab)
        self.findpatient_export_button.setObjectName("findpatient_export_button")
        self.findpatient_layout.addWidget(self.findpatient_export_button, 6, 0, 1, 1)
        self.gridLayout_5.addLayout(self.findpatient_layout, 0, 0, 1, 1)
        self.patient_table = QtWidgets.QTableView(self.credentials_tab)
        self.patient_table.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.patient_table.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.patient_table.setSortingEnabled(True)
        self.patient_table.setObjectName("patient_table")
        self.gridLayout_5.addWidget(self.patient_table, 0, 1, 1, 1)
        self.tab_widget.addTab(self.credentials_tab, "")
        self.examination_tab = QtWidgets.QWidget()
        self.examination_tab.setObjectName("examination_tab")
        self.gridLayout = QtWidgets.QGridLayout(self.examination_tab)
        self.gridLayout.setObjectName("gridLayout")
        self.examination_table = QtWidgets.QTableView(self.examination_tab)
        self.examination_table.setFrameShadow(QtWidgets.QFrame.Plain)
        self.examination_table.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.examination_table.setSortingEnabled(True)
        self.examination_table.setObjectName("examination_table")
        self.gridLayout.addWidget(self.examination_table, 0, 1, 1, 1)
        self.examination_tab_main_layout = QtWidgets.QGroupBox(self.examination_tab)
        self.examination_tab_main_layout.setMinimumSize(QtCore.QSize(0, 0))
        self.examination_tab_main_layout.setMaximumSize(QtCore.QSize(300, 16777215))
        self.examination_tab_main_layout.setTitle("")
        self.examination_tab_main_layout.setObjectName("examination_tab_main_layout")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.examination_tab_main_layout)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.patient_examination_main_label = QtWidgets.QLabel(self.examination_tab_main_layout)
        self.patient_examination_main_label.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.patient_examination_main_label.setFont(font)
        self.patient_examination_main_label.setAlignment(QtCore.Qt.AlignCenter)
        self.patient_examination_main_label.setObjectName("patient_examination_main_label")
        self.gridLayout_6.addWidget(self.patient_examination_main_label, 0, 0, 1, 1)
        self.criteria_box_label = QtWidgets.QLabel(self.examination_tab_main_layout)
        self.criteria_box_label.setMaximumSize(QtCore.QSize(16777215, 15))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.criteria_box_label.setFont(font)
        self.criteria_box_label.setAlignment(QtCore.Qt.AlignCenter)
        self.criteria_box_label.setObjectName("criteria_box_label")
        self.gridLayout_6.addWidget(self.criteria_box_label, 1, 0, 1, 1)
        self.scrollArea = QtWidgets.QScrollArea(self.examination_tab_main_layout)
        self.scrollArea.setMinimumSize(QtCore.QSize(250, 250))
        self.scrollArea.setMaximumSize(QtCore.QSize(250, 16777215))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 248, 272))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.criteria_container_groupbox = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        self.criteria_container_groupbox.setTitle("")
        self.criteria_container_groupbox.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.criteria_container_groupbox.setObjectName("criteria_container_groupbox")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.criteria_container_groupbox)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout_2.addWidget(self.criteria_container_groupbox, 0, 0, 1, 1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout_6.addWidget(self.scrollArea, 2, 0, 1, 1)
        self.modify_criteria_groupbox = QtWidgets.QGroupBox(self.examination_tab_main_layout)
        self.modify_criteria_groupbox.setMinimumSize(QtCore.QSize(0, 0))
        self.modify_criteria_groupbox.setMaximumSize(QtCore.QSize(250, 250))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.modify_criteria_groupbox.setFont(font)
        self.modify_criteria_groupbox.setTitle("")
        self.modify_criteria_groupbox.setObjectName("modify_criteria_groupbox")
        self.A = QtWidgets.QGridLayout(self.modify_criteria_groupbox)
        self.A.setObjectName("A")
        self.criteria_adding_label = QtWidgets.QLabel(self.modify_criteria_groupbox)
        self.criteria_adding_label.setMaximumSize(QtCore.QSize(16777215, 10))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.criteria_adding_label.setFont(font)
        self.criteria_adding_label.setAlignment(QtCore.Qt.AlignCenter)
        self.criteria_adding_label.setObjectName("criteria_adding_label")
        self.A.addWidget(self.criteria_adding_label, 3, 0, 1, 7)
        self.examination_remove_criteria_button = QtWidgets.QPushButton(self.modify_criteria_groupbox)
        self.examination_remove_criteria_button.setMaximumSize(QtCore.QSize(50, 16777215))
        self.examination_remove_criteria_button.setObjectName("examination_remove_criteria_button")
        self.A.addWidget(self.examination_remove_criteria_button, 13, 1, 1, 1)
        self.criteria_modify_label = QtWidgets.QLabel(self.modify_criteria_groupbox)
        self.criteria_modify_label.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.criteria_modify_label.setFont(font)
        self.criteria_modify_label.setAlignment(QtCore.Qt.AlignCenter)
        self.criteria_modify_label.setObjectName("criteria_modify_label")
        self.A.addWidget(self.criteria_modify_label, 1, 0, 1, 7)
        self.line = QtWidgets.QFrame(self.modify_criteria_groupbox)
        self.line.setFrameShadow(QtWidgets.QFrame.Raised)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setObjectName("line")
        self.A.addWidget(self.line, 2, 0, 1, 7)
        self.criteria_removal_le = QtWidgets.QLineEdit(self.modify_criteria_groupbox)
        self.criteria_removal_le.setMaximumSize(QtCore.QSize(80, 16777215))
        self.criteria_removal_le.setObjectName("criteria_removal_le")
        self.A.addWidget(self.criteria_removal_le, 13, 0, 1, 1)
        self.line_2 = QtWidgets.QFrame(self.modify_criteria_groupbox)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.A.addWidget(self.line_2, 10, 0, 1, 7)
        self.criteria_removal_label = QtWidgets.QLabel(self.modify_criteria_groupbox)
        self.criteria_removal_label.setMaximumSize(QtCore.QSize(16777215, 15))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.criteria_removal_label.setFont(font)
        self.criteria_removal_label.setAlignment(QtCore.Qt.AlignCenter)
        self.criteria_removal_label.setObjectName("criteria_removal_label")
        self.A.addWidget(self.criteria_removal_label, 11, 0, 1, 7)
        self.criteria_operator_label = QtWidgets.QLabel(self.modify_criteria_groupbox)
        self.criteria_operator_label.setMaximumSize(QtCore.QSize(16777215, 15))
        self.criteria_operator_label.setObjectName("criteria_operator_label")
        self.A.addWidget(self.criteria_operator_label, 6, 0, 1, 1)
        self.parameter_le = QtWidgets.QLineEdit(self.modify_criteria_groupbox)
        self.parameter_le.setMaximumSize(QtCore.QSize(90, 16777215))
        self.parameter_le.setObjectName("parameter_le")
        self.A.addWidget(self.parameter_le, 7, 1, 1, 1)
        self.criteria_parameter_label = QtWidgets.QLabel(self.modify_criteria_groupbox)
        self.criteria_parameter_label.setMaximumSize(QtCore.QSize(16777215, 15))
        self.criteria_parameter_label.setObjectName("criteria_parameter_label")
        self.A.addWidget(self.criteria_parameter_label, 5, 0, 1, 1)
        self.criteria_parameter_label_2 = QtWidgets.QLabel(self.modify_criteria_groupbox)
        self.criteria_parameter_label_2.setMaximumSize(QtCore.QSize(16777215, 15))
        self.criteria_parameter_label_2.setObjectName("criteria_parameter_label_2")
        self.A.addWidget(self.criteria_parameter_label_2, 7, 0, 1, 1)
        self.parameter_cb = QtWidgets.QComboBox(self.modify_criteria_groupbox)
        self.parameter_cb.setMinimumSize(QtCore.QSize(140, 0))
        self.parameter_cb.setMaximumSize(QtCore.QSize(120, 16777215))
        self.parameter_cb.setObjectName("parameter_cb")
        self.parameter_cb.addItem("")
        self.parameter_cb.setItemText(0, "")
        self.parameter_cb.addItem("")
        self.parameter_cb.addItem("")
        self.parameter_cb.addItem("")
        self.parameter_cb.addItem("")
        self.parameter_cb.addItem("")
        self.parameter_cb.addItem("")
        self.parameter_cb.addItem("")
        self.parameter_cb.addItem("")
        self.parameter_cb.addItem("")
        self.parameter_cb.addItem("")
        self.A.addWidget(self.parameter_cb, 5, 1, 1, 1)
        self.examination_search_button = QtWidgets.QPushButton(self.modify_criteria_groupbox)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.examination_search_button.setFont(font)
        self.examination_search_button.setObjectName("examination_search_button")
        self.A.addWidget(self.examination_search_button, 9, 0, 1, 1)
        self.operator_cb = QtWidgets.QComboBox(self.modify_criteria_groupbox)
        self.operator_cb.setMinimumSize(QtCore.QSize(40, 0))
        self.operator_cb.setMaximumSize(QtCore.QSize(30, 16777215))
        self.operator_cb.setObjectName("operator_cb")
        self.operator_cb.addItem("")
        self.operator_cb.setItemText(0, "")
        self.operator_cb.addItem("")
        self.operator_cb.addItem("")
        self.operator_cb.addItem("")
        self.A.addWidget(self.operator_cb, 6, 1, 1, 1)
        self.examination_search_reset_button = QtWidgets.QPushButton(self.modify_criteria_groupbox)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.examination_search_reset_button.setFont(font)
        self.examination_search_reset_button.setObjectName("examination_search_reset_button")
        self.A.addWidget(self.examination_search_reset_button, 9, 1, 1, 1)
        self.examination_add_criteria_button = QtWidgets.QPushButton(self.modify_criteria_groupbox)
        self.examination_add_criteria_button.setMaximumSize(QtCore.QSize(50, 16777215))
        self.examination_add_criteria_button.setObjectName("examination_add_criteria_button")
        self.A.addWidget(self.examination_add_criteria_button, 8, 0, 1, 1)
        self.gridLayout_6.addWidget(self.modify_criteria_groupbox, 3, 0, 1, 1)
        self.line_3 = QtWidgets.QFrame(self.examination_tab_main_layout)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.gridLayout_6.addWidget(self.line_3, 4, 0, 1, 1)
        self.export_table_label = QtWidgets.QLabel(self.examination_tab_main_layout)
        self.export_table_label.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.export_table_label.setFont(font)
        self.export_table_label.setAlignment(QtCore.Qt.AlignCenter)
        self.export_table_label.setObjectName("export_table_label")
        self.gridLayout_6.addWidget(self.export_table_label, 5, 0, 1, 1)
        self.export_tabledata_button = QtWidgets.QPushButton(self.examination_tab_main_layout)
        self.export_tabledata_button.setObjectName("export_tabledata_button")
        self.gridLayout_6.addWidget(self.export_tabledata_button, 6, 0, 1, 1)
        self.gridLayout.addWidget(self.examination_tab_main_layout, 0, 0, 1, 1)
        self.tab_widget.addTab(self.examination_tab, "")
        self.trend_tab = QtWidgets.QWidget()
        self.trend_tab.setObjectName("trend_tab")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.trend_tab)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.trend_layout = QtWidgets.QGridLayout()
        self.trend_layout.setObjectName("trend_layout")
        self.label_4 = QtWidgets.QLabel(self.trend_tab)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.trend_layout.addWidget(self.label_4, 12, 2, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.trend_tab)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.trend_layout.addWidget(self.label_3, 4, 2, 3, 1)
        spacerItem = QtWidgets.QSpacerItem(5, 5, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.trend_layout.addItem(spacerItem, 16, 2, 1, 2)
        self.trend_patient_table = QtWidgets.QTableView(self.trend_tab)
        self.trend_patient_table.setMinimumSize(QtCore.QSize(950, 0))
        self.trend_patient_table.setMaximumSize(QtCore.QSize(16777215, 80))
        self.trend_patient_table.setObjectName("trend_patient_table")
        self.trend_layout.addWidget(self.trend_patient_table, 4, 3, 8, 1)
        self.trend_pesel_le = QtWidgets.QLineEdit(self.trend_tab)
        self.trend_pesel_le.setObjectName("trend_pesel_le")
        self.trend_layout.addWidget(self.trend_pesel_le, 7, 2, 3, 1)
        self.trend_find_patient_bttn = QtWidgets.QPushButton(self.trend_tab)
        self.trend_find_patient_bttn.setObjectName("trend_find_patient_bttn")
        self.trend_layout.addWidget(self.trend_find_patient_bttn, 10, 2, 2, 1)
        self.trend_plot_button = QtWidgets.QPushButton(self.trend_tab)
        self.trend_plot_button.setObjectName("trend_plot_button")
        self.trend_layout.addWidget(self.trend_plot_button, 14, 2, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.trend_tab)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.trend_layout.addWidget(self.label_5, 0, 2, 1, 2)
        self.trend_examinations_table = QtWidgets.QTableView(self.trend_tab)
        self.trend_examinations_table.setObjectName("trend_examinations_table")
        self.trend_layout.addWidget(self.trend_examinations_table, 17, 2, 1, 2)
        self.trend_examinationtype_le = QtWidgets.QLineEdit(self.trend_tab)
        self.trend_examinationtype_le.setObjectName("trend_examinationtype_le")
        self.trend_layout.addWidget(self.trend_examinationtype_le, 13, 2, 1, 1)
        self.trend_realtime_rb = QtWidgets.QRadioButton(self.trend_tab)
        self.trend_realtime_rb.setObjectName("trend_realtime_rb")
        self.trend_layout.addWidget(self.trend_realtime_rb, 15, 2, 1, 1)
        self.gridLayout_9.addLayout(self.trend_layout, 0, 0, 1, 1)
        self.tab_widget.addTab(self.trend_tab, "")
        self.statistics_tab = QtWidgets.QWidget()
        self.statistics_tab.setObjectName("statistics_tab")
        self.tab_widget.addTab(self.statistics_tab, "")
        self.gridLayout_4.addWidget(self.tab_widget, 0, 0, 1, 1)
        main_app_window.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(main_app_window)
        self.statusbar.setObjectName("statusbar")
        main_app_window.setStatusBar(self.statusbar)

        self.retranslateUi(main_app_window)
        self.tab_widget.setCurrentIndex(3)
        self.findpatient_tab_widget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(main_app_window)
        main_app_window.setTabOrder(self.name_le, self.surname_le)
        main_app_window.setTabOrder(self.surname_le, self.pesel_le)
        main_app_window.setTabOrder(self.pesel_le, self.dateofbirth_le)
        main_app_window.setTabOrder(self.dateofbirth_le, self.gender_cb)
        main_app_window.setTabOrder(self.gender_cb, self.country_cb)
        main_app_window.setTabOrder(self.country_cb, self.phonenumber_le)
        main_app_window.setTabOrder(self.phonenumber_le, self.city_le)
        main_app_window.setTabOrder(self.city_le, self.postalcode_le)
        main_app_window.setTabOrder(self.postalcode_le, self.findpatient_search_button)
        main_app_window.setTabOrder(self.findpatient_search_button, self.findpatient_showall_button)
        main_app_window.setTabOrder(self.findpatient_showall_button, self.findpatient_tab_widget)
        main_app_window.setTabOrder(self.findpatient_tab_widget, self.examination_table)
        main_app_window.setTabOrder(self.examination_table, self.patient_table)

    def retranslateUi(self, main_app_window):
        _translate = QtCore.QCoreApplication.translate
        main_app_window.setWindowTitle(_translate("main_app_window", "MainWindow"))
        self.label.setText(_translate("main_app_window", "Remote Health Monitoring System Application"))
        self.label_2.setText(_translate("main_app_window", "TextLabel"))
        self.tab_widget.setTabText(self.tab_widget.indexOf(self.general_tab), _translate("main_app_window", "General"))
        self.name_label.setText(_translate("main_app_window", "Name"))
        self.pesel_label.setText(_translate("main_app_window", "PESEL"))
        self.surname_label.setText(_translate("main_app_window", "Surname"))
        self.findpatient_tab_widget.setTabText(self.findpatient_tab_widget.indexOf(self.basic_param_tab), _translate("main_app_window", "Basic Search"))
        self.gender_label.setText(_translate("main_app_window", "Gender"))
        self.city_label.setText(_translate("main_app_window", "City"))
        self.phonenumber_label.setText(_translate("main_app_window", "Phone number"))
        self.postalcode_label.setText(_translate("main_app_window", "Postal code"))
        self.country_cb.setItemText(1, _translate("main_app_window", "Afghanistan"))
        self.country_cb.setItemText(2, _translate("main_app_window", "Albania"))
        self.country_cb.setItemText(3, _translate("main_app_window", "Algeria"))
        self.country_cb.setItemText(4, _translate("main_app_window", "American Samoa"))
        self.country_cb.setItemText(5, _translate("main_app_window", "Andorra"))
        self.country_cb.setItemText(6, _translate("main_app_window", "Andola"))
        self.country_cb.setItemText(7, _translate("main_app_window", "Antarctica%"))
        self.country_cb.setItemText(8, _translate("main_app_window", "Antigua and Barbuda"))
        self.country_cb.setItemText(9, _translate("main_app_window", "Argentina"))
        self.country_cb.setItemText(10, _translate("main_app_window", "Armenia"))
        self.country_cb.setItemText(11, _translate("main_app_window", "Aruba"))
        self.country_cb.setItemText(12, _translate("main_app_window", "Australia"))
        self.country_cb.setItemText(13, _translate("main_app_window", "Austria"))
        self.country_cb.setItemText(14, _translate("main_app_window", "Azerbaijan"))
        self.country_cb.setItemText(15, _translate("main_app_window", "Bahamas"))
        self.country_cb.setItemText(16, _translate("main_app_window", "Bahrain"))
        self.country_cb.setItemText(17, _translate("main_app_window", "Bangladesh"))
        self.country_cb.setItemText(18, _translate("main_app_window", "Barbados"))
        self.country_cb.setItemText(19, _translate("main_app_window", "Belarus"))
        self.country_cb.setItemText(20, _translate("main_app_window", "Belgium"))
        self.country_cb.setItemText(21, _translate("main_app_window", "Belize"))
        self.country_cb.setItemText(22, _translate("main_app_window", "Benin"))
        self.country_cb.setItemText(23, _translate("main_app_window", "Bermuda"))
        self.country_cb.setItemText(24, _translate("main_app_window", "Bhutan"))
        self.country_cb.setItemText(25, _translate("main_app_window", "Bolivia"))
        self.country_cb.setItemText(26, _translate("main_app_window", "Bosnia and Herzegovina"))
        self.country_cb.setItemText(27, _translate("main_app_window", "Botswana"))
        self.country_cb.setItemText(28, _translate("main_app_window", "Bouvet Island (Bouvetoya)"))
        self.country_cb.setItemText(29, _translate("main_app_window", "Brazil"))
        self.country_cb.setItemText(30, _translate("main_app_window", "British Indian Ocean Territory%"))
        self.country_cb.setItemText(31, _translate("main_app_window", "British Virgin Islands"))
        self.country_cb.setItemText(32, _translate("main_app_window", "Brunei Darussalam"))
        self.country_cb.setItemText(33, _translate("main_app_window", "Bulgaria"))
        self.country_cb.setItemText(34, _translate("main_app_window", "Burkina Faso"))
        self.country_cb.setItemText(35, _translate("main_app_window", "Burundi"))
        self.country_cb.setItemText(36, _translate("main_app_window", "Cambodia"))
        self.country_cb.setItemText(37, _translate("main_app_window", "Cameroon"))
        self.country_cb.setItemText(38, _translate("main_app_window", "Canada"))
        self.country_cb.setItemText(39, _translate("main_app_window", "Cape Verde"))
        self.country_cb.setItemText(40, _translate("main_app_window", "Cayman Islands"))
        self.country_cb.setItemText(41, _translate("main_app_window", "Central African Republic"))
        self.country_cb.setItemText(42, _translate("main_app_window", "Chad"))
        self.country_cb.setItemText(43, _translate("main_app_window", "Chile"))
        self.country_cb.setItemText(44, _translate("main_app_window", "China"))
        self.country_cb.setItemText(45, _translate("main_app_window", "Christmas Islands"))
        self.country_cb.setItemText(46, _translate("main_app_window", "Cococ (Keeling) Islands"))
        self.country_cb.setItemText(47, _translate("main_app_window", "Colombia"))
        self.country_cb.setItemText(48, _translate("main_app_window", "Congo"))
        self.country_cb.setItemText(49, _translate("main_app_window", "Cook Islands"))
        self.country_cb.setItemText(50, _translate("main_app_window", "Costa Rica"))
        self.country_cb.setItemText(51, _translate("main_app_window", "Cote d\'Ivoire"))
        self.country_cb.setItemText(52, _translate("main_app_window", "Croatia"))
        self.country_cb.setItemText(53, _translate("main_app_window", "Cuba"))
        self.country_cb.setItemText(54, _translate("main_app_window", "Cyprus"))
        self.country_cb.setItemText(55, _translate("main_app_window", "Czech Republic"))
        self.country_cb.setItemText(56, _translate("main_app_window", "Denmark"))
        self.country_cb.setItemText(57, _translate("main_app_window", "Djibouti"))
        self.country_cb.setItemText(58, _translate("main_app_window", "Dominica"))
        self.country_cb.setItemText(59, _translate("main_app_window", "Dominican Republic"))
        self.country_cb.setItemText(60, _translate("main_app_window", "Ecuador"))
        self.country_cb.setItemText(61, _translate("main_app_window", "Egypt"))
        self.country_cb.setItemText(62, _translate("main_app_window", "El Salvador"))
        self.country_cb.setItemText(63, _translate("main_app_window", "Equatorial Guinea"))
        self.country_cb.setItemText(64, _translate("main_app_window", "Eritrea"))
        self.country_cb.setItemText(65, _translate("main_app_window", "Estonia"))
        self.country_cb.setItemText(66, _translate("main_app_window", "Ethiopia"))
        self.country_cb.setItemText(67, _translate("main_app_window", "Falkland Islands (Malvinas)"))
        self.country_cb.setItemText(68, _translate("main_app_window", "Faroe Islands"))
        self.country_cb.setItemText(69, _translate("main_app_window", "Fiji"))
        self.country_cb.setItemText(70, _translate("main_app_window", "Finland"))
        self.country_cb.setItemText(71, _translate("main_app_window", "France"))
        self.country_cb.setItemText(72, _translate("main_app_window", "French Guiana"))
        self.country_cb.setItemText(73, _translate("main_app_window", "French Polynesia"))
        self.country_cb.setItemText(74, _translate("main_app_window", "French Southers Territories"))
        self.country_cb.setItemText(75, _translate("main_app_window", "Gabonn"))
        self.country_cb.setItemText(76, _translate("main_app_window", "Gambia"))
        self.country_cb.setItemText(77, _translate("main_app_window", "Georgia"))
        self.country_cb.setItemText(78, _translate("main_app_window", "Germany"))
        self.country_cb.setItemText(79, _translate("main_app_window", "Ghana"))
        self.country_cb.setItemText(80, _translate("main_app_window", "Gibraltar"))
        self.country_cb.setItemText(81, _translate("main_app_window", "Greece"))
        self.country_cb.setItemText(82, _translate("main_app_window", "Greenland"))
        self.country_cb.setItemText(83, _translate("main_app_window", "Grenada"))
        self.country_cb.setItemText(84, _translate("main_app_window", "Guadeloupe"))
        self.country_cb.setItemText(85, _translate("main_app_window", "Guam"))
        self.country_cb.setItemText(86, _translate("main_app_window", "Guatemala"))
        self.country_cb.setItemText(87, _translate("main_app_window", "Guernsey"))
        self.country_cb.setItemText(88, _translate("main_app_window", "Guinea"))
        self.country_cb.setItemText(89, _translate("main_app_window", "Guinea-Bissau"))
        self.country_cb.setItemText(90, _translate("main_app_window", "Guyana"))
        self.country_cb.setItemText(91, _translate("main_app_window", "Haiti"))
        self.country_cb.setItemText(92, _translate("main_app_window", "Heard Island and McDonald Islands"))
        self.country_cb.setItemText(93, _translate("main_app_window", "Holy See (Vatican City State)"))
        self.country_cb.setItemText(94, _translate("main_app_window", "Honduras"))
        self.country_cb.setItemText(95, _translate("main_app_window", "Hong Kong"))
        self.country_cb.setItemText(96, _translate("main_app_window", "Hungary"))
        self.country_cb.setItemText(97, _translate("main_app_window", "Iceland"))
        self.country_cb.setItemText(98, _translate("main_app_window", "India"))
        self.country_cb.setItemText(99, _translate("main_app_window", "Indonesia"))
        self.country_cb.setItemText(100, _translate("main_app_window", "Iran"))
        self.country_cb.setItemText(101, _translate("main_app_window", "Iraq"))
        self.country_cb.setItemText(102, _translate("main_app_window", "Ireland"))
        self.country_cb.setItemText(103, _translate("main_app_window", "Isle of Man"))
        self.country_cb.setItemText(104, _translate("main_app_window", "Isreal"))
        self.country_cb.setItemText(105, _translate("main_app_window", "Italy"))
        self.country_cb.setItemText(106, _translate("main_app_window", "Jamaica"))
        self.country_cb.setItemText(107, _translate("main_app_window", "Japan"))
        self.country_cb.setItemText(108, _translate("main_app_window", "Jersey"))
        self.country_cb.setItemText(109, _translate("main_app_window", "Jordan"))
        self.country_cb.setItemText(110, _translate("main_app_window", "Kazahstan"))
        self.country_cb.setItemText(111, _translate("main_app_window", "Kenya"))
        self.country_cb.setItemText(112, _translate("main_app_window", "Kiribati"))
        self.country_cb.setItemText(113, _translate("main_app_window", "Korea"))
        self.country_cb.setItemText(114, _translate("main_app_window", "Kuwait"))
        self.country_cb.setItemText(115, _translate("main_app_window", "Kyrgyz Republic"))
        self.country_cb.setItemText(116, _translate("main_app_window", "Lao People\'s Democratic Republic"))
        self.country_cb.setItemText(117, _translate("main_app_window", "Latvia"))
        self.country_cb.setItemText(118, _translate("main_app_window", "Lebanon"))
        self.country_cb.setItemText(119, _translate("main_app_window", "Lesotho"))
        self.country_cb.setItemText(120, _translate("main_app_window", "Liberia"))
        self.country_cb.setItemText(121, _translate("main_app_window", "Libyan Arab Jamahiriya"))
        self.country_cb.setItemText(122, _translate("main_app_window", "Liechtenstein"))
        self.country_cb.setItemText(123, _translate("main_app_window", "Lithuania"))
        self.country_cb.setItemText(124, _translate("main_app_window", "Luxembourg"))
        self.country_cb.setItemText(125, _translate("main_app_window", "Macao"))
        self.country_cb.setItemText(126, _translate("main_app_window", "Macedonia"))
        self.country_cb.setItemText(127, _translate("main_app_window", "Madagascar"))
        self.country_cb.setItemText(128, _translate("main_app_window", "Malawi"))
        self.country_cb.setItemText(129, _translate("main_app_window", "Malaysia"))
        self.country_cb.setItemText(130, _translate("main_app_window", "Maldives"))
        self.country_cb.setItemText(131, _translate("main_app_window", "Mali"))
        self.country_cb.setItemText(132, _translate("main_app_window", "Malta"))
        self.country_cb.setItemText(133, _translate("main_app_window", "Marshall Islands"))
        self.country_cb.setItemText(134, _translate("main_app_window", "Martinique"))
        self.country_cb.setItemText(135, _translate("main_app_window", "Mauritania"))
        self.country_cb.setItemText(136, _translate("main_app_window", "Maurtitius"))
        self.country_cb.setItemText(137, _translate("main_app_window", "Mayotte"))
        self.country_cb.setItemText(138, _translate("main_app_window", "Mexico"))
        self.country_cb.setItemText(139, _translate("main_app_window", "Micronesia"))
        self.country_cb.setItemText(140, _translate("main_app_window", "Moldova"))
        self.country_cb.setItemText(141, _translate("main_app_window", "Monaco"))
        self.country_cb.setItemText(142, _translate("main_app_window", "Mongolia"))
        self.country_cb.setItemText(143, _translate("main_app_window", "Montenegro"))
        self.country_cb.setItemText(144, _translate("main_app_window", "Montserrat"))
        self.country_cb.setItemText(145, _translate("main_app_window", "Morocco"))
        self.country_cb.setItemText(146, _translate("main_app_window", "Mozambique"))
        self.country_cb.setItemText(147, _translate("main_app_window", "Myanmar"))
        self.country_cb.setItemText(148, _translate("main_app_window", "Namibia"))
        self.country_cb.setItemText(149, _translate("main_app_window", "Nauru"))
        self.country_cb.setItemText(150, _translate("main_app_window", "Nepal"))
        self.country_cb.setItemText(151, _translate("main_app_window", "Netherlands"))
        self.country_cb.setItemText(152, _translate("main_app_window", "Netherlands Antilles"))
        self.country_cb.setItemText(153, _translate("main_app_window", "New Caledonia"))
        self.country_cb.setItemText(154, _translate("main_app_window", "New Zealand"))
        self.country_cb.setItemText(155, _translate("main_app_window", "Nicaragua"))
        self.country_cb.setItemText(156, _translate("main_app_window", "Niger"))
        self.country_cb.setItemText(157, _translate("main_app_window", "Nigeria"))
        self.country_cb.setItemText(158, _translate("main_app_window", "Niue"))
        self.country_cb.setItemText(159, _translate("main_app_window", "Norfolk Island"))
        self.country_cb.setItemText(160, _translate("main_app_window", "Northern Marian Islands"))
        self.country_cb.setItemText(161, _translate("main_app_window", "Norway"))
        self.country_cb.setItemText(162, _translate("main_app_window", "Oman"))
        self.country_cb.setItemText(163, _translate("main_app_window", "Pakistan"))
        self.country_cb.setItemText(164, _translate("main_app_window", "Palau"))
        self.country_cb.setItemText(165, _translate("main_app_window", "Palestinian Territory"))
        self.country_cb.setItemText(166, _translate("main_app_window", "Panama"))
        self.country_cb.setItemText(167, _translate("main_app_window", "Papua New Guinea"))
        self.country_cb.setItemText(168, _translate("main_app_window", "Paraguay"))
        self.country_cb.setItemText(169, _translate("main_app_window", "Peru"))
        self.country_cb.setItemText(170, _translate("main_app_window", "Philippines"))
        self.country_cb.setItemText(171, _translate("main_app_window", "Pitcairn Islands"))
        self.country_cb.setItemText(172, _translate("main_app_window", "Poland"))
        self.country_cb.setItemText(173, _translate("main_app_window", "Portugal"))
        self.country_cb.setItemText(174, _translate("main_app_window", "Puerto Rico"))
        self.country_cb.setItemText(175, _translate("main_app_window", "Qatar"))
        self.country_cb.setItemText(176, _translate("main_app_window", "Reunion"))
        self.country_cb.setItemText(177, _translate("main_app_window", "Romania"))
        self.country_cb.setItemText(178, _translate("main_app_window", "Russian Federation"))
        self.country_cb.setItemText(179, _translate("main_app_window", "Rwanda"))
        self.country_cb.setItemText(180, _translate("main_app_window", "Saint Barthelemy"))
        self.country_cb.setItemText(181, _translate("main_app_window", "Saint Helena"))
        self.country_cb.setItemText(182, _translate("main_app_window", "Saint Kitts and Nevis"))
        self.country_cb.setItemText(183, _translate("main_app_window", "Saint Lucia"))
        self.country_cb.setItemText(184, _translate("main_app_window", "Saint Martin"))
        self.country_cb.setItemText(185, _translate("main_app_window", "Saint Pierre and Miquelon"))
        self.country_cb.setItemText(186, _translate("main_app_window", "Saint Vincent and the Grenadines"))
        self.country_cb.setItemText(187, _translate("main_app_window", "Samoa"))
        self.country_cb.setItemText(188, _translate("main_app_window", "San Marino"))
        self.country_cb.setItemText(189, _translate("main_app_window", "Sao Tome and Principe"))
        self.country_cb.setItemText(190, _translate("main_app_window", "Saudi Arabia"))
        self.country_cb.setItemText(191, _translate("main_app_window", "Senegal"))
        self.country_cb.setItemText(192, _translate("main_app_window", "Serbia"))
        self.country_cb.setItemText(193, _translate("main_app_window", "Seychelles"))
        self.country_cb.setItemText(194, _translate("main_app_window", "Sierra Leona"))
        self.country_cb.setItemText(195, _translate("main_app_window", "Singapore"))
        self.country_cb.setItemText(196, _translate("main_app_window", "Slovakia (Slovak Republic)"))
        self.country_cb.setItemText(197, _translate("main_app_window", "Slovenia"))
        self.country_cb.setItemText(198, _translate("main_app_window", "Solomon Islands"))
        self.country_cb.setItemText(199, _translate("main_app_window", "Somalia"))
        self.country_cb.setItemText(200, _translate("main_app_window", "South Africa"))
        self.country_cb.setItemText(201, _translate("main_app_window", "South Georgia and the South Sandwich Islands"))
        self.country_cb.setItemText(202, _translate("main_app_window", "Spain"))
        self.country_cb.setItemText(203, _translate("main_app_window", "Sri Lanka"))
        self.country_cb.setItemText(204, _translate("main_app_window", "Sudan"))
        self.country_cb.setItemText(205, _translate("main_app_window", "Suriname"))
        self.country_cb.setItemText(206, _translate("main_app_window", "Svalbard & Jan Mayen Islands"))
        self.country_cb.setItemText(207, _translate("main_app_window", "Swaziland"))
        self.country_cb.setItemText(208, _translate("main_app_window", "Sweden"))
        self.country_cb.setItemText(209, _translate("main_app_window", "Switzerland"))
        self.country_cb.setItemText(210, _translate("main_app_window", "Syrian Arab Republic"))
        self.country_cb.setItemText(211, _translate("main_app_window", "Taiwan"))
        self.country_cb.setItemText(212, _translate("main_app_window", "Tajikistan"))
        self.country_cb.setItemText(213, _translate("main_app_window", "Tanzania"))
        self.country_cb.setItemText(214, _translate("main_app_window", "Thailand"))
        self.country_cb.setItemText(215, _translate("main_app_window", "Timor-Leste"))
        self.country_cb.setItemText(216, _translate("main_app_window", "Togo"))
        self.country_cb.setItemText(217, _translate("main_app_window", "Tokelau"))
        self.country_cb.setItemText(218, _translate("main_app_window", "Tonga"))
        self.country_cb.setItemText(219, _translate("main_app_window", "Trinidad and Tobago"))
        self.country_cb.setItemText(220, _translate("main_app_window", "Tunisia"))
        self.country_cb.setItemText(221, _translate("main_app_window", "Turkey"))
        self.country_cb.setItemText(222, _translate("main_app_window", "Turkmenistan"))
        self.country_cb.setItemText(223, _translate("main_app_window", "Turks and Caicos Islands"))
        self.country_cb.setItemText(224, _translate("main_app_window", "Tuvalu"))
        self.country_cb.setItemText(225, _translate("main_app_window", "Uganda"))
        self.country_cb.setItemText(226, _translate("main_app_window", "Ukraine"))
        self.country_cb.setItemText(227, _translate("main_app_window", "United Arab Emirates"))
        self.country_cb.setItemText(228, _translate("main_app_window", "United Kingdom"))
        self.country_cb.setItemText(229, _translate("main_app_window", "United States Minor Outlying Islands"))
        self.country_cb.setItemText(230, _translate("main_app_window", "United States of America"))
        self.country_cb.setItemText(231, _translate("main_app_window", "United States Virgin Islands"))
        self.country_cb.setItemText(232, _translate("main_app_window", "Uruguay"))
        self.country_cb.setItemText(233, _translate("main_app_window", "Uzbekistan"))
        self.country_cb.setItemText(234, _translate("main_app_window", "Vanuatu"))
        self.country_cb.setItemText(235, _translate("main_app_window", "Venezuela"))
        self.country_cb.setItemText(236, _translate("main_app_window", "Vietnam"))
        self.country_cb.setItemText(237, _translate("main_app_window", "Wallis and Futuna"))
        self.country_cb.setItemText(238, _translate("main_app_window", "Western Sahara"))
        self.country_cb.setItemText(239, _translate("main_app_window", "Yemen"))
        self.country_cb.setItemText(240, _translate("main_app_window", "Zambia"))
        self.country_cb.setItemText(241, _translate("main_app_window", "Zimbabwe"))
        self.country_label.setText(_translate("main_app_window", "Country"))
        self.gender_cb.setItemText(1, _translate("main_app_window", "M"))
        self.gender_cb.setItemText(2, _translate("main_app_window", "F"))
        self.dateofbirth_label.setText(_translate("main_app_window", "Date of birth"))
        self.findpatient_tab_widget.setTabText(self.findpatient_tab_widget.indexOf(self.adv_param_tab), _translate("main_app_window", "Advanced Search"))
        self.findpatient_showall_button.setText(_translate("main_app_window", "Show All"))
        self.enable_a_search.setText(_translate("main_app_window", "Find Many"))
        self.findpatient_search_button.setText(_translate("main_app_window", "Search"))
        self.findpatient_label.setText(_translate("main_app_window", "Find a patient"))
        self.findpatient_export_button.setText(_translate("main_app_window", "Export"))
        self.tab_widget.setTabText(self.tab_widget.indexOf(self.credentials_tab), _translate("main_app_window", "Patient Credentials"))
        self.patient_examination_main_label.setText(_translate("main_app_window", "Patient Examination"))
        self.criteria_box_label.setText(_translate("main_app_window", "Selected Criteria"))
        self.criteria_adding_label.setText(_translate("main_app_window", "Add criteria - Choose criteria options"))
        self.examination_remove_criteria_button.setText(_translate("main_app_window", "Remove"))
        self.criteria_modify_label.setText(_translate("main_app_window", "Add or remove criteria"))
        self.criteria_removal_label.setText(_translate("main_app_window", "Remove criteria - Write criteria index"))
        self.criteria_operator_label.setText(_translate("main_app_window", "Operator"))
        self.criteria_parameter_label.setText(_translate("main_app_window", "Parameter"))
        self.criteria_parameter_label_2.setText(_translate("main_app_window", "Parameter Value"))
        self.parameter_cb.setItemText(1, _translate("main_app_window", "Name"))
        self.parameter_cb.setItemText(2, _translate("main_app_window", "Surname"))
        self.parameter_cb.setItemText(3, _translate("main_app_window", "Examination Date"))
        self.parameter_cb.setItemText(4, _translate("main_app_window", "Systolic Pressure"))
        self.parameter_cb.setItemText(5, _translate("main_app_window", "Diastolic Pressure"))
        self.parameter_cb.setItemText(6, _translate("main_app_window", "Heart Rate"))
        self.parameter_cb.setItemText(7, _translate("main_app_window", "Patient Height"))
        self.parameter_cb.setItemText(8, _translate("main_app_window", "Patient Weight"))
        self.parameter_cb.setItemText(9, _translate("main_app_window", "BMI"))
        self.parameter_cb.setItemText(10, _translate("main_app_window", "Parameter Warning"))
        self.examination_search_button.setText(_translate("main_app_window", "Search"))
        self.operator_cb.setItemText(1, _translate("main_app_window", ">"))
        self.operator_cb.setItemText(2, _translate("main_app_window", "<"))
        self.operator_cb.setItemText(3, _translate("main_app_window", "="))
        self.examination_search_reset_button.setText(_translate("main_app_window", "Reset and show all"))
        self.examination_add_criteria_button.setText(_translate("main_app_window", "Add"))
        self.export_table_label.setText(_translate("main_app_window", "Export Table"))
        self.export_tabledata_button.setText(_translate("main_app_window", "Export"))
        self.tab_widget.setTabText(self.tab_widget.indexOf(self.examination_tab), _translate("main_app_window", "Patient Examination"))
        self.label_4.setText(_translate("main_app_window", "Type Examination Type"))
        self.label_3.setText(_translate("main_app_window", "Type PESEL number"))
        self.trend_pesel_le.setText(_translate("main_app_window", "65957022551"))
        self.trend_find_patient_bttn.setText(_translate("main_app_window", "Find Patient"))
        self.trend_plot_button.setText(_translate("main_app_window", "Plot Examination Parameters"))
        self.label_5.setText(_translate("main_app_window", "Examination Parameters Plotting"))
        self.trend_examinationtype_le.setText(_translate("main_app_window", "BMI"))
        self.trend_realtime_rb.setText(_translate("main_app_window", "Enable Real-Time plotting"))
        self.tab_widget.setTabText(self.tab_widget.indexOf(self.trend_tab), _translate("main_app_window", "Trend"))
        self.tab_widget.setTabText(self.tab_widget.indexOf(self.statistics_tab), _translate("main_app_window", "Statistics"))

